; battle_anim_struct members (see macros/wram.asm)
	const_def
	const BATTLEANIMSTRUCT_INDEX
	const BATTLEANIMSTRUCT_OAMFLAGS
	const BATTLEANIMSTRUCT_FIX_Y
	const BATTLEANIMSTRUCT_FRAMESET_ID
	const BATTLEANIMSTRUCT_FUNCTION
	const BATTLEANIMSTRUCT_TILEID
DEF BATTLEANIMOBJ_LENGTH EQU const_value - 1
	const BATTLEANIMSTRUCT_XCOORD
	const BATTLEANIMSTRUCT_YCOORD
	const BATTLEANIMSTRUCT_XOFFSET
	const BATTLEANIMSTRUCT_YOFFSET
	const BATTLEANIMSTRUCT_PARAM
	const BATTLEANIMSTRUCT_DURATION
	const BATTLEANIMSTRUCT_FRAME
	const BATTLEANIMSTRUCT_JUMPTABLE_INDEX
	const BATTLEANIMSTRUCT_VAR1
	const BATTLEANIMSTRUCT_VAR2
DEF BATTLEANIMSTRUCT_LENGTH EQU const_value
DEF NUM_BATTLE_ANIM_STRUCTS EQU 10 ; see wActiveAnimObjects

DEF BATTLEANIMSTRUCT_OAMFLAGS_FIX_COORDS_F EQU 0

; wBattleAnimTileDict size (see wram.asm)
DEF NUM_BATTLEANIMTILEDICT_ENTRIES EQU 5

; Start tile for battle animation graphics
DEF BATTLEANIM_BASE_TILE EQU 7 * 7  ; Maximum size of a pokemon picture

; BattleAnimObjects indexes (see data/battle_anims/objects.asm)
	const_def
	const ANIM_OBJ_00
	const ANIM_OBJ_01
	const ANIM_OBJ_02
	const ANIM_OBJ_03
	const ANIM_OBJ_04
	const ANIM_OBJ_05
	const ANIM_OBJ_06
	const ANIM_OBJ_07
	const ANIM_OBJ_08
	const ANIM_OBJ_FANG
	const ANIM_OBJ_0A
	const ANIM_OBJ_EMBER
	const ANIM_OBJ_DRAGON_RAGE
	const ANIM_OBJ_FLAMETHROWER
	const ANIM_OBJ_FIRE_SPIN
	const ANIM_OBJ_FIRE_BLAST
	const ANIM_OBJ_BURNED
	const ANIM_OBJ_BLIZZARD
	const ANIM_OBJ_12
	const ANIM_OBJ_ICE_BEAM
	const ANIM_OBJ_RAZOR_LEAF
	const ANIM_OBJ_POKE_BALL
	const ANIM_OBJ_POKE_BALL_BLOCKED
	const ANIM_OBJ_17
	const ANIM_OBJ_18
	const ANIM_OBJ_19
	const ANIM_OBJ_1A
	const ANIM_OBJ_1B
	const ANIM_OBJ_BALL_POOF
	const ANIM_OBJ_BIG_ROCK
	const ANIM_OBJ_SMALL_ROCK
	const ANIM_OBJ_STRENGTH
	const ANIM_OBJ_SEISMIC_TOSS
	const ANIM_OBJ_BUBBLE
	const ANIM_OBJ_SURF
	const ANIM_OBJ_SING
	const ANIM_OBJ_WATER_GUN
	const ANIM_OBJ_HYDRO_PUMP
	const ANIM_OBJ_POWDER
	const ANIM_OBJ_27
	const ANIM_OBJ_28
	const ANIM_OBJ_ICE_BUILDUP
	const ANIM_OBJ_FROZEN
	const ANIM_OBJ_MASTER_BALL_SPARKLE
	const ANIM_OBJ_RECOVER
	const ANIM_OBJ_2D
	const ANIM_OBJ_2E
	const ANIM_OBJ_2F
	const ANIM_OBJ_THUNDER_WAVE
	const ANIM_OBJ_31
	const ANIM_OBJ_LIGHTNING_BOLT
	const ANIM_OBJ_33
	const ANIM_OBJ_34
	const ANIM_OBJ_CLAMP
	const ANIM_OBJ_BITE
	const ANIM_OBJ_37
	const ANIM_OBJ_38
	const ANIM_OBJ_39
	const ANIM_OBJ_3A
	const ANIM_OBJ_3B
	const ANIM_OBJ_3C
	const ANIM_OBJ_3D
	const ANIM_OBJ_GUST
	const ANIM_OBJ_3F
	const ANIM_OBJ_40
	const ANIM_OBJ_41
	const ANIM_OBJ_42
	const ANIM_OBJ_SONICBOOM_JP
	const ANIM_OBJ_44
	const ANIM_OBJ_ABSORB
	const ANIM_OBJ_EGG
	const ANIM_OBJ_47
	const ANIM_OBJ_48
	const ANIM_OBJ_49
	const ANIM_OBJ_LEECH_SEED
	const ANIM_OBJ_4B
	const ANIM_OBJ_WAVE
	const ANIM_OBJ_CONFUSE_RAY
	const ANIM_OBJ_4E
	const ANIM_OBJ_4F
	const ANIM_OBJ_SCREEN
	const ANIM_OBJ_HARDEN
	const ANIM_OBJ_CHICK
	const ANIM_OBJ_AMNESIA
	const ANIM_OBJ_ASLEEP
	const ANIM_OBJ_SKULL
	const ANIM_OBJ_56
	const ANIM_OBJ_57
	const ANIM_OBJ_58
	const ANIM_OBJ_PARALYZED
	const ANIM_OBJ_STRING_SHOT
	const ANIM_OBJ_HAZE
	const ANIM_OBJ_MIST
	const ANIM_OBJ_SMOG
	const ANIM_OBJ_POISON_GAS
	const ANIM_OBJ_HORN
	const ANIM_OBJ_60
	const ANIM_OBJ_PETAL_DANCE
	const ANIM_OBJ_SLUDGE_BOMB
	const ANIM_OBJ_PAY_DAY
	const ANIM_OBJ_64
	const ANIM_OBJ_MIMIC
	const ANIM_OBJ_ATTRACT
	const ANIM_OBJ_BONEMERANG
	const ANIM_OBJ_BONE_CLUB
	const ANIM_OBJ_BONE_RUSH
	const ANIM_OBJ_SWIFT
	const ANIM_OBJ_KINESIS
	const ANIM_OBJ_FLASH
	const ANIM_OBJ_SHINY
	const ANIM_OBJ_SKY_ATTACK
	const ANIM_OBJ_LICK
	const ANIM_OBJ_WITHDRAW
	const ANIM_OBJ_71
	const ANIM_OBJ_GROWTH
	const ANIM_OBJ_CONVERSION2
	const ANIM_OBJ_SMOKE
	const ANIM_OBJ_SMOKESCREEN
	const ANIM_OBJ_SWORDS_DANCE
	const ANIM_OBJ_SPEED_LINE
	const ANIM_OBJ_SHARPEN
	const ANIM_OBJ_DEFENSE_CURL
	const ANIM_OBJ_7A
	const ANIM_OBJ_7B
	const ANIM_OBJ_DISABLE
	const ANIM_OBJ_AGILITY
	const ANIM_OBJ_HEART
	const ANIM_OBJ_FLAME_WHEEL
	const ANIM_OBJ_SACRED_FIRE
	const ANIM_OBJ_COTTON_SPORE
	const ANIM_OBJ_MILK_DRINK
	const ANIM_OBJ_ANGER
	const ANIM_OBJ_84
	const ANIM_OBJ_85
	const ANIM_OBJ_BATON_PASS
	const ANIM_OBJ_LOCK_ON
	const ANIM_OBJ_MIND_READER
	const ANIM_OBJ_SAFEGUARD
	const ANIM_OBJ_PROTECT
	const ANIM_OBJ_THIEF
	const ANIM_OBJ_OCTAZOOKA
	const ANIM_OBJ_PRESENT
	const ANIM_OBJ_SPIKES
	const ANIM_OBJ_POWDER_SNOW
	const ANIM_OBJ_DRAGONBREATH
	const ANIM_OBJ_CONVERSION
	const ANIM_OBJ_SPIDER_WEB
	const ANIM_OBJ_93
	const ANIM_OBJ_NIGHTMARE
	const ANIM_OBJ_IN_NIGHTMARE
	const ANIM_OBJ_LOVELY_KISS
	const ANIM_OBJ_SWEET_KISS
	const ANIM_OBJ_SKETCH
	const ANIM_OBJ_99
	const ANIM_OBJ_9A
	const ANIM_OBJ_DESTINY_BOND
	const ANIM_OBJ_MORNING_SUN
	const ANIM_OBJ_GLIMMER
	const ANIM_OBJ_MOONLIGHT
	const ANIM_OBJ_HIDDEN_POWER
	const ANIM_OBJ_A0
	const ANIM_OBJ_A1
	const ANIM_OBJ_SANDSTORM
	const ANIM_OBJ_ZAP_CANNON
	const ANIM_OBJ_SPITE
	const ANIM_OBJ_CURSE
	const ANIM_OBJ_PERISH_SONG
	const ANIM_OBJ_FORESIGHT
	const ANIM_OBJ_RAPID_SPIN
	const ANIM_OBJ_SWAGGER
	const ANIM_OBJ_AA
	const ANIM_OBJ_AB
	const ANIM_OBJ_MEAN_LOOK
	const ANIM_OBJ_AD
	const ANIM_OBJ_AE
	const ANIM_OBJ_RAIN
	const ANIM_OBJ_B0
	const ANIM_OBJ_PSYCH_UP
	const ANIM_OBJ_ANCIENTPOWER
	const ANIM_OBJ_AEROBLAST
	const ANIM_OBJ_SHADOW_BALL
	const ANIM_OBJ_ROCK_SMASH
	const ANIM_OBJ_FLOWER
	const ANIM_OBJ_COTTON

DEF const_value = $b1
	const ANIM_OBJ_PLAYERFEETFOLLOW
	const ANIM_OBJ_ENEMYFEETFOLLOW
	const ANIM_OBJ_PLAYERHEADFOLLOW
	const ANIM_OBJ_ENEMYHEADFOLLOW

; DoBattleAnimFrame arguments (see engine/battle_anims/functions.asm)
	const_def
	const BATTLE_ANIM_FUNC_NULL                      ; 00
	const BATTLE_ANIM_FUNC_USER_TO_TARGET            ; 01
	const BATTLE_ANIM_FUNC_USER_TO_TARGET_DISAPPEAR  ; 02
	const BATTLE_ANIM_FUNC_MOVE_IN_CIRCLE            ; 03
	const BATTLE_ANIM_FUNC_WAVE_TO_TARGET            ; 04
	const BATTLE_ANIM_FUNC_THROW_TO_TARGET           ; 05
	const BATTLE_ANIM_FUNC_THROW_TO_TARGET_DISAPPEAR ; 06
	const BATTLE_ANIM_FUNC_DROP                      ; 07
	const BATTLE_ANIM_FUNC_USER_TO_TARGET_SPIN       ; 08
	const BATTLE_ANIM_FUNC_SHAKE                     ; 09
	const BATTLE_ANIM_FUNC_FIRE_BLAST                ; 0a
	const BATTLE_ANIM_FUNC_RAZOR_LEAF                ; 0b
	const BATTLE_ANIM_FUNC_BUBBLE                    ; 0c
	const BATTLE_ANIM_FUNC_SURF                      ; 0d
	const BATTLE_ANIM_FUNC_SING                      ; 0e
	const BATTLE_ANIM_FUNC_WATER_GUN                 ; 0f
	const BATTLE_ANIM_FUNC_EMBER                     ; 10
	const BATTLE_ANIM_FUNC_POWDER                    ; 11
	const BATTLE_ANIM_FUNC_POKEBALL                  ; 12
	const BATTLE_ANIM_FUNC_POKEBALL_BLOCKED          ; 13
	const BATTLE_ANIM_FUNC_RECOVER                   ; 14
	const BATTLE_ANIM_FUNC_THUNDER_WAVE              ; 15
	const BATTLE_ANIM_FUNC_CLAMP_ENCORE              ; 16
	const BATTLE_ANIM_FUNC_BITE                      ; 17
	const BATTLE_ANIM_FUNC_SOLAR_BEAM                ; 18
	const BATTLE_ANIM_FUNC_GUST                      ; 19
	const BATTLE_ANIM_FUNC_RAZOR_WIND                ; 1a
	const BATTLE_ANIM_FUNC_KICK                      ; 1b
	const BATTLE_ANIM_FUNC_ABSORB                    ; 1c
	const BATTLE_ANIM_FUNC_EGG                       ; 1d
	const BATTLE_ANIM_FUNC_MOVE_UP                   ; 1e
	const BATTLE_ANIM_FUNC_WRAP                      ; 1f
	const BATTLE_ANIM_FUNC_LEECH_SEED                ; 20
	const BATTLE_ANIM_FUNC_SOUND                     ; 21
	const BATTLE_ANIM_FUNC_CONFUSE_RAY               ; 22
	const BATTLE_ANIM_FUNC_DIZZY                     ; 23
	const BATTLE_ANIM_FUNC_AMNESIA                   ; 24
	const BATTLE_ANIM_FUNC_FLOAT_UP                  ; 25
	const BATTLE_ANIM_FUNC_DIG                       ; 26
	const BATTLE_ANIM_FUNC_STRING                    ; 27
	const BATTLE_ANIM_FUNC_PARALYZED                 ; 28
	const BATTLE_ANIM_FUNC_SPIRAL_DESCENT            ; 29
	const BATTLE_ANIM_FUNC_POISON_GAS                ; 2a
	const BATTLE_ANIM_FUNC_HORN                      ; 2b
	const BATTLE_ANIM_FUNC_NEEDLE                    ; 2c
	const BATTLE_ANIM_FUNC_PETAL_DANCE               ; 2d
	const BATTLE_ANIM_FUNC_THIEF_PAYDAY              ; 2e
	const BATTLE_ANIM_FUNC_ABSORB_CIRCLE             ; 2f
	const BATTLE_ANIM_FUNC_BONEMERANG                ; 30
	const BATTLE_ANIM_FUNC_SHINY                     ; 31
	const BATTLE_ANIM_FUNC_SKY_ATTACK                ; 32
	const BATTLE_ANIM_FUNC_GROWTH_SWORDS_DANCE       ; 33
	const BATTLE_ANIM_FUNC_SMOKE_FLAME_WHEEL         ; 34
	const BATTLE_ANIM_FUNC_PRESENT_SMOKESCREEN       ; 35
	const BATTLE_ANIM_FUNC_STRENGTH_SEISMIC_TOSS     ; 36
	const BATTLE_ANIM_FUNC_SPEED_LINE                ; 37
	const BATTLE_ANIM_FUNC_SLUDGE                    ; 38
	const BATTLE_ANIM_FUNC_METRONOME_HAND            ; 39
	const BATTLE_ANIM_FUNC_METRONOME_SPARKLE_SKETCH  ; 3a
	const BATTLE_ANIM_FUNC_AGILITY                   ; 3b
	const BATTLE_ANIM_FUNC_SACRED_FIRE               ; 3c
	const BATTLE_ANIM_FUNC_SAFEGUARD_PROTECT         ; 3d
	const BATTLE_ANIM_FUNC_LOCK_ON_MIND_READER       ; 3e
	const BATTLE_ANIM_FUNC_SPIKES                    ; 3f
	const BATTLE_ANIM_FUNC_HEAL_BELL_NOTES           ; 40
	const BATTLE_ANIM_FUNC_BATON_PASS                ; 41
	const BATTLE_ANIM_FUNC_CONVERSION                ; 42
	const BATTLE_ANIM_FUNC_ENCORE_BELLY_DRUM         ; 43
	const BATTLE_ANIM_FUNC_SWAGGER_MORNING_SUN       ; 44
	const BATTLE_ANIM_FUNC_HIDDEN_POWER              ; 45
	const BATTLE_ANIM_FUNC_CURSE                     ; 46
	const BATTLE_ANIM_FUNC_PERISH_SONG               ; 47
	const BATTLE_ANIM_FUNC_RAPID_SPIN                ; 48
	const BATTLE_ANIM_FUNC_BETA_PURSUIT              ; 49
	const BATTLE_ANIM_FUNC_RAIN_SANDSTORM            ; 4a
DEF NUM_BATTLE_ANIM_FUNCS EQU const_value

; BattleAnimFrameData indexes (see data/battle_anims/framesets.asm)
	const_def
	const BATTLE_ANIM_FRAMESET_00
	const BATTLE_ANIM_FRAMESET_01
	const BATTLE_ANIM_FRAMESET_02
	const BATTLE_ANIM_FRAMESET_03
	const BATTLE_ANIM_FRAMESET_04
	const BATTLE_ANIM_FRAMESET_05
	const BATTLE_ANIM_FRAMESET_06
	const BATTLE_ANIM_FRAMESET_07
	const BATTLE_ANIM_FRAMESET_08
	const BATTLE_ANIM_FRAMESET_POKE_BALL_1
	const BATTLE_ANIM_FRAMESET_POKE_BALL_2
	const BATTLE_ANIM_FRAMESET_POKE_BALL_3
	const BATTLE_ANIM_FRAMESET_POKE_BALL_4
	const BATTLE_ANIM_FRAMESET_POKE_BALL_5
	const BATTLE_ANIM_FRAMESET_0E
	const BATTLE_ANIM_FRAMESET_FLAMETHROWER
	const BATTLE_ANIM_FRAMESET_EMBER
	const BATTLE_ANIM_FRAMESET_BURNED
	const BATTLE_ANIM_FRAMESET_12
	const BATTLE_ANIM_FRAMESET_13
	const BATTLE_ANIM_FRAMESET_14
	const BATTLE_ANIM_FRAMESET_15
	const BATTLE_ANIM_FRAMESET_RAZOR_LEAF_1
	const BATTLE_ANIM_FRAMESET_RAZOR_LEAF_2
	const BATTLE_ANIM_FRAMESET_18
	const BATTLE_ANIM_FRAMESET_19
	const BATTLE_ANIM_FRAMESET_1A
	const BATTLE_ANIM_FRAMESET_1B
	const BATTLE_ANIM_FRAMESET_1C
	const BATTLE_ANIM_FRAMESET_1D
	const BATTLE_ANIM_FRAMESET_1E
	const BATTLE_ANIM_FRAMESET_1F
	const BATTLE_ANIM_FRAMESET_SLUDGE_BUBBLE_BURST
	const BATTLE_ANIM_FRAMESET_21
	const BATTLE_ANIM_FRAMESET_PULSING_BUBBLE
	const BATTLE_ANIM_FRAMESET_23
	const BATTLE_ANIM_FRAMESET_MUSIC_NOTE_1
	const BATTLE_ANIM_FRAMESET_MUSIC_NOTE_2
	const BATTLE_ANIM_FRAMESET_MUSIC_NOTE_3
	const BATTLE_ANIM_FRAMESET_WATER_GUN_1
	const BATTLE_ANIM_FRAMESET_WATER_GUN_2
	const BATTLE_ANIM_FRAMESET_WATER_GUN_3
	const BATTLE_ANIM_FRAMESET_2A
	const BATTLE_ANIM_FRAMESET_2B
	const BATTLE_ANIM_FRAMESET_2C
	const BATTLE_ANIM_FRAMESET_2D
	const BATTLE_ANIM_FRAMESET_2E
	const BATTLE_ANIM_FRAMESET_2F
	const BATTLE_ANIM_FRAMESET_30
	const BATTLE_ANIM_FRAMESET_31
	const BATTLE_ANIM_FRAMESET_32
	const BATTLE_ANIM_FRAMESET_33
	const BATTLE_ANIM_FRAMESET_34
	const BATTLE_ANIM_FRAMESET_THUNDER_WAVE_EXTRA
	const BATTLE_ANIM_FRAMESET_36
	const BATTLE_ANIM_FRAMESET_37
	const BATTLE_ANIM_FRAMESET_38
	const BATTLE_ANIM_FRAMESET_39
	const BATTLE_ANIM_FRAMESET_3A
	const BATTLE_ANIM_FRAMESET_3B
	const BATTLE_ANIM_FRAMESET_BITE_1
	const BATTLE_ANIM_FRAMESET_BITE_2
	const BATTLE_ANIM_FRAMESET_3E
	const BATTLE_ANIM_FRAMESET_3F
	const BATTLE_ANIM_FRAMESET_40
	const BATTLE_ANIM_FRAMESET_41
	const BATTLE_ANIM_FRAMESET_42
	const BATTLE_ANIM_FRAMESET_43
	const BATTLE_ANIM_FRAMESET_44
	const BATTLE_ANIM_FRAMESET_45
	const BATTLE_ANIM_FRAMESET_46
	const BATTLE_ANIM_FRAMESET_47
	const BATTLE_ANIM_FRAMESET_48
	const BATTLE_ANIM_FRAMESET_49
	const BATTLE_ANIM_FRAMESET_4A
	const BATTLE_ANIM_FRAMESET_4B
	const BATTLE_ANIM_FRAMESET_4C
	const BATTLE_ANIM_FRAMESET_4D
	const BATTLE_ANIM_FRAMESET_EGG_WOBBLE
	const BATTLE_ANIM_FRAMESET_EGG_CRACKED_TOP
	const BATTLE_ANIM_FRAMESET_EGG_CRACKED_BOTTOM
	const BATTLE_ANIM_FRAMESET_51
	const BATTLE_ANIM_FRAMESET_52
	const BATTLE_ANIM_FRAMESET_53
	const BATTLE_ANIM_FRAMESET_54
	const BATTLE_ANIM_FRAMESET_55
	const BATTLE_ANIM_FRAMESET_LEECH_SEED
	const BATTLE_ANIM_FRAMESET_LEECH_SEED_2
	const BATTLE_ANIM_FRAMESET_LEECH_SEED_3
	const BATTLE_ANIM_FRAMESET_SOUND_1
	const BATTLE_ANIM_FRAMESET_SOUND_2
	const BATTLE_ANIM_FRAMESET_SOUND_3
	const BATTLE_ANIM_FRAMESET_5C
	const BATTLE_ANIM_FRAMESET_CONFUSE_RAY_1
	const BATTLE_ANIM_FRAMESET_CONFUSE_RAY_2
	const BATTLE_ANIM_FRAMESET_5F
	const BATTLE_ANIM_FRAMESET_60
	const BATTLE_ANIM_FRAMESET_61
	const BATTLE_ANIM_FRAMESET_62
	const BATTLE_ANIM_FRAMESET_AMNESIA_1
	const BATTLE_ANIM_FRAMESET_AMNESIA_2
	const BATTLE_ANIM_FRAMESET_AMNESIA_3
	const BATTLE_ANIM_FRAMESET_66
	const BATTLE_ANIM_FRAMESET_67
	const BATTLE_ANIM_FRAMESET_68
	const BATTLE_ANIM_FRAMESET_69
	const BATTLE_ANIM_FRAMESET_STRING_SHOT_1
	const BATTLE_ANIM_FRAMESET_STRING_SHOT_2
	const BATTLE_ANIM_FRAMESET_STRING_SHOT_3
	const BATTLE_ANIM_FRAMESET_6D
	const BATTLE_ANIM_FRAMESET_PARALYZED_FLIPPED
	const BATTLE_ANIM_FRAMESET_6F
	const BATTLE_ANIM_FRAMESET_70
	const BATTLE_ANIM_FRAMESET_71
	const BATTLE_ANIM_FRAMESET_72
	const BATTLE_ANIM_FRAMESET_73
	const BATTLE_ANIM_FRAMESET_74
	const BATTLE_ANIM_FRAMESET_75
	const BATTLE_ANIM_FRAMESET_76
	const BATTLE_ANIM_FRAMESET_77
	const BATTLE_ANIM_FRAMESET_78
	const BATTLE_ANIM_FRAMESET_79
	const BATTLE_ANIM_FRAMESET_7A
	const BATTLE_ANIM_FRAMESET_7B
	const BATTLE_ANIM_FRAMESET_7C
	const BATTLE_ANIM_FRAMESET_7D
	const BATTLE_ANIM_FRAMESET_7E
	const BATTLE_ANIM_FRAMESET_7F
	const BATTLE_ANIM_FRAMESET_80
	const BATTLE_ANIM_FRAMESET_SPEED_LINE_1
	const BATTLE_ANIM_FRAMESET_SPEED_LINE_2
	const BATTLE_ANIM_FRAMESET_SPEED_LINE_3
	const BATTLE_ANIM_FRAMESET_84
	const BATTLE_ANIM_FRAMESET_85
	const BATTLE_ANIM_FRAMESET_86
	const BATTLE_ANIM_FRAMESET_87
	const BATTLE_ANIM_FRAMESET_88
	const BATTLE_ANIM_FRAMESET_89
	const BATTLE_ANIM_FRAMESET_8A
	const BATTLE_ANIM_FRAMESET_8B
	const BATTLE_ANIM_FRAMESET_8C
	const BATTLE_ANIM_FRAMESET_8D
	const BATTLE_ANIM_FRAMESET_8E
	const BATTLE_ANIM_FRAMESET_8F
	const BATTLE_ANIM_FRAMESET_90
	const BATTLE_ANIM_FRAMESET_91
	const BATTLE_ANIM_FRAMESET_92
	const BATTLE_ANIM_FRAMESET_93
	const BATTLE_ANIM_FRAMESET_94
	const BATTLE_ANIM_FRAMESET_95
	const BATTLE_ANIM_FRAMESET_96
	const BATTLE_ANIM_FRAMESET_97
	const BATTLE_ANIM_FRAMESET_98
	const BATTLE_ANIM_FRAMESET_99
	const BATTLE_ANIM_FRAMESET_9A
	const BATTLE_ANIM_FRAMESET_9B
	const BATTLE_ANIM_FRAMESET_9C
	const BATTLE_ANIM_FRAMESET_9D
	const BATTLE_ANIM_FRAMESET_9E
	const BATTLE_ANIM_FRAMESET_9F
	const BATTLE_ANIM_FRAMESET_A0
	const BATTLE_ANIM_FRAMESET_A1
	const BATTLE_ANIM_FRAMESET_A2
	const BATTLE_ANIM_FRAMESET_A3
	const BATTLE_ANIM_FRAMESET_A4
	const BATTLE_ANIM_FRAMESET_A5
	const BATTLE_ANIM_FRAMESET_A6
	const BATTLE_ANIM_FRAMESET_A7
	const BATTLE_ANIM_FRAMESET_A8
	const BATTLE_ANIM_FRAMESET_A9
	const BATTLE_ANIM_FRAMESET_AA
	const BATTLE_ANIM_FRAMESET_AB
	const BATTLE_ANIM_FRAMESET_AC
	const BATTLE_ANIM_FRAMESET_AD
	const BATTLE_ANIM_FRAMESET_AE
	const BATTLE_ANIM_FRAMESET_AF
	const BATTLE_ANIM_FRAMESET_B0
	const BATTLE_ANIM_FRAMESET_B1
	const BATTLE_ANIM_FRAMESET_B2
	const BATTLE_ANIM_FRAMESET_B3
	const BATTLE_ANIM_FRAMESET_B4
	const BATTLE_ANIM_FRAMESET_B5
	const BATTLE_ANIM_FRAMESET_B6
	const BATTLE_ANIM_FRAMESET_B7
	const BATTLE_ANIM_FRAMESET_B8

; BattleAnimOAMData indexes (see data/battle_anims/oam.asm)
	const_def
	const BATTLE_ANIM_OAMSET_00
	const BATTLE_ANIM_OAMSET_01
	const BATTLE_ANIM_OAMSET_02
	const BATTLE_ANIM_OAMSET_03
	const BATTLE_ANIM_OAMSET_04
	const BATTLE_ANIM_OAMSET_05
	const BATTLE_ANIM_OAMSET_06
	const BATTLE_ANIM_OAMSET_07
	const BATTLE_ANIM_OAMSET_08
	const BATTLE_ANIM_OAMSET_09
	const BATTLE_ANIM_OAMSET_0A
	const BATTLE_ANIM_OAMSET_0B
	const BATTLE_ANIM_OAMSET_0C
	const BATTLE_ANIM_OAMSET_0D
	const BATTLE_ANIM_OAMSET_0E
	const BATTLE_ANIM_OAMSET_0F
	const BATTLE_ANIM_OAMSET_10
	const BATTLE_ANIM_OAMSET_11
	const BATTLE_ANIM_OAMSET_12
	const BATTLE_ANIM_OAMSET_13
	const BATTLE_ANIM_OAMSET_14
	const BATTLE_ANIM_OAMSET_15
	const BATTLE_ANIM_OAMSET_16
	const BATTLE_ANIM_OAMSET_17
	const BATTLE_ANIM_OAMSET_18
	const BATTLE_ANIM_OAMSET_19
	const BATTLE_ANIM_OAMSET_1A
	const BATTLE_ANIM_OAMSET_1B
	const BATTLE_ANIM_OAMSET_1C
	const BATTLE_ANIM_OAMSET_1D
	const BATTLE_ANIM_OAMSET_1E
	const BATTLE_ANIM_OAMSET_1F
	const BATTLE_ANIM_OAMSET_20
	const BATTLE_ANIM_OAMSET_21
	const BATTLE_ANIM_OAMSET_22
	const BATTLE_ANIM_OAMSET_23
	const BATTLE_ANIM_OAMSET_24
	const BATTLE_ANIM_OAMSET_25
	const BATTLE_ANIM_OAMSET_26
	const BATTLE_ANIM_OAMSET_27
	const BATTLE_ANIM_OAMSET_28
	const BATTLE_ANIM_OAMSET_29
	const BATTLE_ANIM_OAMSET_2A
	const BATTLE_ANIM_OAMSET_2B
	const BATTLE_ANIM_OAMSET_2C
	const BATTLE_ANIM_OAMSET_2D
	const BATTLE_ANIM_OAMSET_2E
	const BATTLE_ANIM_OAMSET_2F
	const BATTLE_ANIM_OAMSET_30
	const BATTLE_ANIM_OAMSET_31
	const BATTLE_ANIM_OAMSET_32
	const BATTLE_ANIM_OAMSET_33
	const BATTLE_ANIM_OAMSET_34
	const BATTLE_ANIM_OAMSET_35
	const BATTLE_ANIM_OAMSET_36
	const BATTLE_ANIM_OAMSET_37
	const BATTLE_ANIM_OAMSET_38
	const BATTLE_ANIM_OAMSET_39
	const BATTLE_ANIM_OAMSET_3A
	const BATTLE_ANIM_OAMSET_3B
	const BATTLE_ANIM_OAMSET_3C
	const BATTLE_ANIM_OAMSET_3D
	const BATTLE_ANIM_OAMSET_3E
	const BATTLE_ANIM_OAMSET_3F
	const BATTLE_ANIM_OAMSET_40
	const BATTLE_ANIM_OAMSET_41
	const BATTLE_ANIM_OAMSET_42
	const BATTLE_ANIM_OAMSET_43
	const BATTLE_ANIM_OAMSET_44
	const BATTLE_ANIM_OAMSET_45
	const BATTLE_ANIM_OAMSET_46
	const BATTLE_ANIM_OAMSET_47
	const BATTLE_ANIM_OAMSET_48
	const BATTLE_ANIM_OAMSET_49
	const BATTLE_ANIM_OAMSET_4A
	const BATTLE_ANIM_OAMSET_4B
	const BATTLE_ANIM_OAMSET_4C
	const BATTLE_ANIM_OAMSET_4D
	const BATTLE_ANIM_OAMSET_4E
	const BATTLE_ANIM_OAMSET_4F
	const BATTLE_ANIM_OAMSET_50
	const BATTLE_ANIM_OAMSET_51
	const BATTLE_ANIM_OAMSET_52
	const BATTLE_ANIM_OAMSET_53
	const BATTLE_ANIM_OAMSET_54
	const BATTLE_ANIM_OAMSET_55
	const BATTLE_ANIM_OAMSET_56
	const BATTLE_ANIM_OAMSET_57
	const BATTLE_ANIM_OAMSET_58
	const BATTLE_ANIM_OAMSET_59
	const BATTLE_ANIM_OAMSET_5A
	const BATTLE_ANIM_OAMSET_5B
	const BATTLE_ANIM_OAMSET_5C
	const BATTLE_ANIM_OAMSET_5D
	const BATTLE_ANIM_OAMSET_5E
	const BATTLE_ANIM_OAMSET_5F
	const BATTLE_ANIM_OAMSET_60
	const BATTLE_ANIM_OAMSET_61
	const BATTLE_ANIM_OAMSET_62
	const BATTLE_ANIM_OAMSET_63
	const BATTLE_ANIM_OAMSET_64
	const BATTLE_ANIM_OAMSET_65
	const BATTLE_ANIM_OAMSET_66
	const BATTLE_ANIM_OAMSET_67
	const BATTLE_ANIM_OAMSET_68
	const BATTLE_ANIM_OAMSET_69
	const BATTLE_ANIM_OAMSET_6A
	const BATTLE_ANIM_OAMSET_6B
	const BATTLE_ANIM_OAMSET_6C
	const BATTLE_ANIM_OAMSET_6D
	const BATTLE_ANIM_OAMSET_6E
	const BATTLE_ANIM_OAMSET_6F
	const BATTLE_ANIM_OAMSET_70
	const BATTLE_ANIM_OAMSET_71
	const BATTLE_ANIM_OAMSET_72
	const BATTLE_ANIM_OAMSET_73
	const BATTLE_ANIM_OAMSET_74
	const BATTLE_ANIM_OAMSET_75
	const BATTLE_ANIM_OAMSET_76
	const BATTLE_ANIM_OAMSET_77
	const BATTLE_ANIM_OAMSET_78
	const BATTLE_ANIM_OAMSET_79
	const BATTLE_ANIM_OAMSET_7A
	const BATTLE_ANIM_OAMSET_7B
	const BATTLE_ANIM_OAMSET_7C
	const BATTLE_ANIM_OAMSET_7D
	const BATTLE_ANIM_OAMSET_7E
	const BATTLE_ANIM_OAMSET_7F
	const BATTLE_ANIM_OAMSET_80
	const BATTLE_ANIM_OAMSET_81
	const BATTLE_ANIM_OAMSET_82
	const BATTLE_ANIM_OAMSET_83
	const BATTLE_ANIM_OAMSET_84
	const BATTLE_ANIM_OAMSET_85
	const BATTLE_ANIM_OAMSET_86
	const BATTLE_ANIM_OAMSET_87
	const BATTLE_ANIM_OAMSET_88
	const BATTLE_ANIM_OAMSET_89
	const BATTLE_ANIM_OAMSET_8A
	const BATTLE_ANIM_OAMSET_8B
	const BATTLE_ANIM_OAMSET_8C
	const BATTLE_ANIM_OAMSET_8D
	const BATTLE_ANIM_OAMSET_8E
	const BATTLE_ANIM_OAMSET_8F
	const BATTLE_ANIM_OAMSET_90
	const BATTLE_ANIM_OAMSET_91
	const BATTLE_ANIM_OAMSET_92
	const BATTLE_ANIM_OAMSET_93
	const BATTLE_ANIM_OAMSET_94
	const BATTLE_ANIM_OAMSET_95
	const BATTLE_ANIM_OAMSET_96
	const BATTLE_ANIM_OAMSET_97
	const BATTLE_ANIM_OAMSET_98
	const BATTLE_ANIM_OAMSET_99
	const BATTLE_ANIM_OAMSET_9A
	const BATTLE_ANIM_OAMSET_9B
	const BATTLE_ANIM_OAMSET_9C
	const BATTLE_ANIM_OAMSET_9D
	const BATTLE_ANIM_OAMSET_9E
	const BATTLE_ANIM_OAMSET_9F
	const BATTLE_ANIM_OAMSET_A0
	const BATTLE_ANIM_OAMSET_A1
	const BATTLE_ANIM_OAMSET_A2
	const BATTLE_ANIM_OAMSET_A3
	const BATTLE_ANIM_OAMSET_A4
	const BATTLE_ANIM_OAMSET_A5
	const BATTLE_ANIM_OAMSET_A6
	const BATTLE_ANIM_OAMSET_A7
	const BATTLE_ANIM_OAMSET_A8
	const BATTLE_ANIM_OAMSET_A9
	const BATTLE_ANIM_OAMSET_AA
	const BATTLE_ANIM_OAMSET_AB
	const BATTLE_ANIM_OAMSET_AC
	const BATTLE_ANIM_OAMSET_AD
	const BATTLE_ANIM_OAMSET_AE
	const BATTLE_ANIM_OAMSET_AF
	const BATTLE_ANIM_OAMSET_B0
	const BATTLE_ANIM_OAMSET_B1
	const BATTLE_ANIM_OAMSET_B2
	const BATTLE_ANIM_OAMSET_B3
	const BATTLE_ANIM_OAMSET_B4
	const BATTLE_ANIM_OAMSET_B5
	const BATTLE_ANIM_OAMSET_B6
	const BATTLE_ANIM_OAMSET_B7
	const BATTLE_ANIM_OAMSET_B8
	const BATTLE_ANIM_OAMSET_B9
	const BATTLE_ANIM_OAMSET_BA
	const BATTLE_ANIM_OAMSET_BB
	const BATTLE_ANIM_OAMSET_BC
	const BATTLE_ANIM_OAMSET_BD
	const BATTLE_ANIM_OAMSET_BE
	const BATTLE_ANIM_OAMSET_BF
	const BATTLE_ANIM_OAMSET_C0
	const BATTLE_ANIM_OAMSET_C1
	const BATTLE_ANIM_OAMSET_C2
	const BATTLE_ANIM_OAMSET_C3
	const BATTLE_ANIM_OAMSET_C4
	const BATTLE_ANIM_OAMSET_C5
	const BATTLE_ANIM_OAMSET_C6
	const BATTLE_ANIM_OAMSET_C7
	const BATTLE_ANIM_OAMSET_C8
	const BATTLE_ANIM_OAMSET_C9
	const BATTLE_ANIM_OAMSET_CA
	const BATTLE_ANIM_OAMSET_CB
	const BATTLE_ANIM_OAMSET_CC
	const BATTLE_ANIM_OAMSET_CD
	const BATTLE_ANIM_OAMSET_CE
	const BATTLE_ANIM_OAMSET_CF
	const BATTLE_ANIM_OAMSET_D0
	const BATTLE_ANIM_OAMSET_D1
	const BATTLE_ANIM_OAMSET_D2
DEF NUM_BATTLE_ANIM_OAMSETS EQU const_value

; BattleBGEffects indexes (see engine/battle_anims/bg_effects.asm)
	const_def 1
	const ANIM_BG_FLASH_INVERTED
	const ANIM_BG_FLASH_WHITE
	const ANIM_BG_WHITE_HUES
	const ANIM_BG_BLACK_HUES
	const ANIM_BG_ALTERNATE_HUES
	const ANIM_BG_06
	const ANIM_BG_07
	const ANIM_BG_08
	const ANIM_BG_HIDE_MON
	const ANIM_BG_SHOW_MON
	const ANIM_BG_ENTER_MON
	const ANIM_BG_RETURN_MON
	const ANIM_BG_SURF
	;const ANIM_BG_WHIRLPOOL
	const ANIM_BG_TELEPORT
	const ANIM_BG_NIGHT_SHADE
	const ANIM_BG_FEET_FOLLOW
	const ANIM_BG_HEAD_FOLLOW
	const ANIM_BG_DOUBLE_TEAM
	const ANIM_BG_ACID_ARMOR
	const ANIM_BG_RAPID_FLASH
	const ANIM_BG_16
	const ANIM_BG_17
	const ANIM_BG_18
	const ANIM_BG_19
	const ANIM_BG_1A
	const ANIM_BG_1B
	const ANIM_BG_1C
	const ANIM_BG_1D
	const ANIM_BG_1E
	const ANIM_BG_1F
	const ANIM_BG_20
	const ANIM_BG_WITHDRAW
	const ANIM_BG_BOUNCE_DOWN
	const ANIM_BG_DIG
	const ANIM_BG_TACKLE
	;const ANIM_BG_25
	const ANIM_BG_26
	const ANIM_BG_27
	const ANIM_BG_WAVE_DEFORM_USER
	const ANIM_BG_PSYCHIC
	const ANIM_BG_2A
	const ANIM_BG_2B
	const ANIM_BG_2C
	const ANIM_BG_2D
	const ANIM_BG_2E
	const ANIM_BG_2F
	;const ANIM_BG_30
	;const ANIM_BG_31
	;const ANIM_BG_32
	;const ANIM_BG_VIBRATE_MON
	;const ANIM_BG_WOBBLE_MON
	;const ANIM_BG_35

; wBattleAnimTileDict keys (see wram.asm)
; AnimObjGFX indexes (see data/battle_anims/object_gfx.asm)
	const_def 1
	const BATTLE_ANIM_GFX_HIT        ; 01
	const BATTLE_ANIM_GFX_CUT        ; 02
	const BATTLE_ANIM_GFX_FIRE       ; 03
	const BATTLE_ANIM_GFX_WATER      ; 04
	const BATTLE_ANIM_GFX_LIGHTNING  ; 05
	const BATTLE_ANIM_GFX_PLANT      ; 06
	const BATTLE_ANIM_GFX_SMOKE      ; 07
	const BATTLE_ANIM_GFX_EXPLOSION  ; 08
	const BATTLE_ANIM_GFX_ROCKS      ; 09
	const BATTLE_ANIM_GFX_ICE        ; 0a
	const BATTLE_ANIM_GFX_POKE_BALL  ; 0b
	const BATTLE_ANIM_GFX_POISON     ; 0c
	const BATTLE_ANIM_GFX_BUBBLE     ; 0d
	const BATTLE_ANIM_GFX_NOISE      ; 0e
	const BATTLE_ANIM_GFX_POWDER     ; 0f
	const BATTLE_ANIM_GFX_BEAM       ; 10
	const BATTLE_ANIM_GFX_SPEED      ; 11
	const BATTLE_ANIM_GFX_CHARGE     ; 12
	const BATTLE_ANIM_GFX_WIND       ; 13
	const BATTLE_ANIM_GFX_WHIP       ; 14
	const BATTLE_ANIM_GFX_EGG        ; 15
	const BATTLE_ANIM_GFX_ROPE       ; 16
	const BATTLE_ANIM_GFX_PSYCHIC    ; 17
	const BATTLE_ANIM_GFX_REFLECT    ; 18
	const BATTLE_ANIM_GFX_STATUS     ; 19
	const BATTLE_ANIM_GFX_SAND       ; 1a
	const BATTLE_ANIM_GFX_WEB        ; 1b
	const BATTLE_ANIM_GFX_HAZE       ; 1c
	const BATTLE_ANIM_GFX_HORN       ; 1d
	const BATTLE_ANIM_GFX_FLOWER     ; 1e
	const BATTLE_ANIM_GFX_MISC       ; 1f
	const BATTLE_ANIM_GFX_SKY_ATTACK ; 20
	const BATTLE_ANIM_GFX_GLOBE      ; 21
	const BATTLE_ANIM_GFX_SHAPES     ; 22
	const BATTLE_ANIM_GFX_OBJECTS    ; 23
	const BATTLE_ANIM_GFX_SHINE      ; 24
	const BATTLE_ANIM_GFX_ANGELS     ; 25
	const BATTLE_ANIM_GFX_PLAYERHEAD ; 26
	const BATTLE_ANIM_GFX_ENEMYFEET  ; 27
DEF NUM_BATTLE_ANIM_GFX EQU const_value - 1

; battle_bg_effect struct members (see macros/wram.asm)
	const_def
	const BG_EFFECT_STRUCT_FUNCTION
	const BG_EFFECT_STRUCT_JT_INDEX
	const BG_EFFECT_STRUCT_BATTLE_TURN
	const BG_EFFECT_STRUCT_PARAM
DEF BG_EFFECT_STRUCT_LENGTH EQU const_value
DEF NUM_BG_EFFECTS EQU 5 ; see wActiveBGEffects

; battle palettes
	const_def
	const PAL_BATTLE_BG_PLAYER    ; 0
	const PAL_BATTLE_BG_ENEMY     ; 1
	const PAL_BATTLE_BG_ENEMY_HP  ; 2
	const PAL_BATTLE_BG_PLAYER_HP ; 3
	const PAL_BATTLE_BG_EXP       ; 4
	const PAL_BATTLE_BG_5         ; 5
	const PAL_BATTLE_BG_6         ; 6
	const PAL_BATTLE_BG_TEXT      ; 7

; animation object palettes
	const_def
	const PAL_BATTLE_OB_ENEMY  ; 0
	const PAL_BATTLE_OB_PLAYER ; 1
	const PAL_BATTLE_OB_GRAY   ; 2
	const PAL_BATTLE_OB_YELLOW ; 3
	const PAL_BATTLE_OB_RED    ; 4
	const PAL_BATTLE_OB_GREEN  ; 5
	const PAL_BATTLE_OB_BLUE   ; 6
	const PAL_BATTLE_OB_BROWN  ; 7
