; Icon IDs
	const_def
	const ICON_NONE        ; 00
	const ICON_NYOROMO     ; 01
	const ICON_PURIN       ; 02
	const ICON_DIGDA       ; 03
	const ICON_PIKACHU     ; 04
	const ICON_HITODEMAN   ; 05
	const ICON_KOIKING     ; 06
	const ICON_POPPO       ; 07
	const ICON_SIDON       ; 08
	const ICON_PIPPI       ; 09
	const ICON_NAZONOKUSA  ; 0a
	const ICON_MUSHI       ; 0b
	const ICON_GANGAR      ; 0c
	const ICON_LAPLACE     ; 0d
	const ICON_BARRIERD    ; 0e
	const ICON_LOKON       ; 0f
	const ICON_KENTAUROS   ; 10
	const ICON_SHELLDER    ; 11
	const ICON_METAMON     ; 12
	const ICON_IWARK       ; 13
	const ICON_BIRIRIDAMA  ; 14
	const ICON_ZENIGAME    ; 15
	const ICON_FUSHIGIDANE ; 16
	const ICON_HITOKAGE    ; 17
	const ICON_BEEDLE      ; 18
	const ICON_ANNON       ; 19
	const ICON_ISITSUBUTE  ; 1a
	const ICON_WANRIKY     ; 1b
	const ICON_EGG         ; 1c
	const ICON_MENOKURAGE  ; 1d
	const ICON_BUTTERFREE  ; 1e
	const ICON_ZUBAT       ; 1f
	const ICON_KABIGON     ; 20
