	const_def
	const LANDMARK_NONE               ; 00
	const LANDMARK_SILENT             ; 01
	const LANDMARK_OLD                ; 02
	const LANDMARK_WEST               ; 03
	const LANDMARK_HIGH_TECH          ; 04
	const LANDMARK_FOUNT              ; 05
	const LANDMARK_BIRDON             ; 06
	const LANDMARK_NEW_TYPE           ; 07
	const LANDMARK_SUGAR              ; 08
	const LANDMARK_BLUE_FOREST        ; 09
	const LANDMARK_STAND              ; 0a
	const LANDMARK_KANTO              ; 0b
	const LANDMARK_PRINCE             ; 0c
	const LANDMARK_MT_FUJI            ; 0d
	const LANDMARK_SOUTH              ; 0e
	const LANDMARK_NORTH              ; 0f
	const LANDMARK_ROUTE_15           ; 10
	const LANDMARK_ROUTE_18           ; 11
	const LANDMARK_POWER_PLANT_1      ; 12
	const LANDMARK_POWER_PLANT_2      ; 13
	const LANDMARK_POWER_PLANT_3      ; 14
	const LANDMARK_POWER_PLANT_4      ; 15
	const LANDMARK_RUINS_1            ; 16
	const LANDMARK_RUINS_2            ; 17
	const LANDMARK_MINES_1            ; 18
	const LANDMARK_MINES_2            ; 19
	const LANDMARK_MINES_3            ; 1a
	const LANDMARK_MINES_4            ; 1b
	const LANDMARK_MINES_5            ; 1c
	const LANDMARK_MINES_6            ; 1d
	const LANDMARK_MINES_7            ; 1e
	const LANDMARK_HIDEOUT_1          ; 1f
	const LANDMARK_HIDEOUT_2          ; 20
	const LANDMARK_HIDEOUT_3          ; 21
	const LANDMARK_SLOWPOKE_WELL_1    ; 22
	const LANDMARK_SLOWPOKE_WELL_2    ; 23
	const LANDMARK_POKEMON_LEAGUE_1   ; 24
	const LANDMARK_POKEMON_LEAGUE_1_2 ; 25
	const LANDMARK_POKEMON_LEAGUE_2   ; 26
	const LANDMARK_POKEMON_LEAGUE_3   ; 27
	const LANDMARK_POKEMON_LEAGUE_4   ; 28
	const LANDMARK_POKEMON_LEAGUE_5   ; 29
	const LANDMARK_POKEMON_LEAGUE_6   ; 2a
	const LANDMARK_POKEMON_LEAGUE_7   ; 2b
	const LANDMARK_POKEMON_LEAGUE_7_2 ; 2c
	const LANDMARK_SILENT_HILL        ; 2d
