	const_def
	const LANDMARK_NONE                     ; 00
	const LANDMARK_NORTH                    ; 01
	const LANDMARK_BULL_FOREST_ROUTE_3      ; 02
	const LANDMARK_BULL_FOREST              ; 03
	const LANDMARK_BULL_FOREST_ROUTE_2      ; 04
	const LANDMARK_STAND                    ; 05
	const LANDMARK_STAND_ROUTE              ; 06
	const LANDMARK_KANTO_EAST_ROUTE         ; 07
	const LANDMARK_KANTO                    ; 08
	const LANDMARK_ROUTE_SILENT_EAST        ; 09
	const LANDMARK_SILENT_HILL              ; 0a
	const LANDMARK_PRINCE                   ; 0b
	const LANDMARK_MT_FUJI                  ; 0c
	const LANDMARK_ROUTE_1_P1               ; 0d
	const LANDMARK_ROUTE_1_P2               ; 0e
	const LANDMARK_OLD_CITY                 ; 0f
	const LANDMARK_ROUTE_2                  ; 10
	const LANDMARK_WEST                     ; 11
	const LANDMARK_BAADON_ROUTE_1           ; 12
	const LANDMARK_BAADON                   ; 13
	const LANDMARK_BAADON_ROUTE_2           ; 14
	const LANDMARK_BAADON_ROUTE_3           ; 15
	const LANDMARK_ROUTE_15                 ; 16
	const LANDMARK_NEWTYPE                  ; 17
	const LANDMARK_SUGAR_ROUTE              ; 18
	const LANDMARK_SUGAR                    ; 19
	const LANDMARK_NEWTYPE_ROUTE            ; 1a
	const LANDMARK_ROUTE_18                 ; 1b
	const LANDMARK_BULL_FOREST_ROUTE_1      ; 1c
	const LANDMARK_1C                       ; 1d
	const LANDMARK_1D                       ; 1e
	const LANDMARK_FONTO_ROUTE_3            ; 1f
	const LANDMARK_FONTO                    ; 20
	const LANDMARK_FONTO_ROUTE_2            ; 21
	const LANDMARK_FONTO_ROUTE_6            ; 22
	const LANDMARK_FONTO_ROUTE_5            ; 23
	const LANDMARK_SOUTH                    ; 24
	const LANDMARK_FONTO_ROUTE_1            ; 25
	const LANDMARK_HAITEKU_WEST_ROUTE_OCEAN ; 26
	const LANDMARK_HAITEKU_WEST_ROUTE       ; 27
	const LANDMARK_HAITEKU                  ; 28
	const LANDMARK_WASTE_BRIDGE             ; 29
	const LANDMARK_FONTO_ROUTE_4            ; 2a
	const LANDMARK_FONTO_BRIDGE             ; 2b
