	const_def
	const LANDMARK_NONE                       ; 00
	const LANDMARK_NORTH                      ; 01
	const LANDMARK_ROUTE_26                   ; 02
	const LANDMARK_BLUE_FOREST                ; 03
	const LANDMARK_ROUTE_20                   ; 04
	const LANDMARK_STAND                      ; 05
	const LANDMARK_ROUTE_21                   ; 06
	const LANDMARK_ROUTE_22                   ; 07
	const LANDMARK_KANTO                      ; 08
	const LANDMARK_ROUTE_23                   ; 09
	const LANDMARK_SILENT_HILL                ; 0a
	const LANDMARK_PRINCE                     ; 0b
	const LANDMARK_MT_FUJI                    ; 0c
	const LANDMARK_ROUTE_1                    ; 0d
	const LANDMARK_ROUTE_2                    ; 0e
	const LANDMARK_OLD_CITY                   ; 0f
	const LANDMARK_ROUTE_3                    ; 10
	const LANDMARK_WEST                       ; 11
	const LANDMARK_ROUTE_4                    ; 12
	const LANDMARK_BIRDON                     ; 13
	const LANDMARK_ROUTE_13                   ; 14
	const LANDMARK_ROUTE_14                   ; 15
	const LANDMARK_ROUTE_15                   ; 16
	const LANDMARK_NEWTYPE                    ; 17
	const LANDMARK_ROUTE_16                   ; 18
	const LANDMARK_SUGAR                      ; 19
	const LANDMARK_ROUTE_17                   ; 1a
	const LANDMARK_ROUTE_18                   ; 1b
	const LANDMARK_ROUTE_19                   ; 1c
	const LANDMARK_1C                         ; 1d
	const LANDMARK_1D                         ; 1e
	const LANDMARK_ROUTE_11                   ; 1f
	const LANDMARK_FONT                       ; 20
	const LANDMARK_ROUTE_10                   ; 21
	const LANDMARK_ROUTE_25                   ; 22
	const LANDMARK_ROUTE_24                   ; 23
	const LANDMARK_SOUTH                      ; 24
	const LANDMARK_ROUTE_9                    ; 25
	const LANDMARK_HIGH_TECH_WEST_ROUTE_OCEAN ; 26
	const LANDMARK_HIGH_TECH_WEST_ROUTE       ; 27
	const LANDMARK_HIGH_TECH                  ; 28
	const LANDMARK_ROUTE_5                    ; 29
	const LANDMARK_ROUTE_12                   ; 2a
	const LANDMARK_ROUTE_8                ; 2b
