	rsreset
DEF OBJECT_SPRITE              rb 1 ; 00
DEF OBJECT_MAP_OBJECT_INDEX    rb 1 ; 01
DEF OBJECT_SPRITE_TILE         rb 1 ; 02
DEF OBJECT_MOVEMENTTYPE        rb 1 ; 03
DEF OBJECT_FLAGS               rw 1 ; 04
DEF OBJECT_PALETTE             rb 1 ; 06
DEF OBJECT_DIRECTION_WALKING   rb 1 ; 07
DEF OBJECT_FACING              rb 1 ; 08
DEF OBJECT_STEP_TYPE           rb 1 ; 09
DEF OBJECT_STEP_DURATION       rb 1 ; 0a
DEF OBJECT_ACTION              rb 1 ; 0b
DEF OBJECT_STEP_FRAME          rb 1 ; 0c
DEF OBJECT_FACING_STEP         rb 1 ; 0d
DEF OBJECT_NEXT_TILE           rb 1 ; 0e
DEF OBJECT_STANDING_TILE       rb 1 ; 0f
DEF OBJECT_NEXT_MAP_X          rb 1 ; 10
DEF OBJECT_NEXT_MAP_Y          rb 1 ; 11
DEF OBJECT_MAP_X               rb 1 ; 12
DEF OBJECT_MAP_Y               rb 1 ; 13
DEF OBJECT_INIT_X              rb 1 ; 14
DEF OBJECT_INIT_Y              rb 1 ; 15
DEF OBJECT_RADIUS              rb 1 ; 16
DEF OBJECT_SPRITE_X            rb 1 ; 17
DEF OBJECT_SPRITE_Y            rb 1 ; 18
DEF OBJECT_SPRITE_X_OFFSET     rb 1 ; 19
DEF OBJECT_SPRITE_Y_OFFSET     rb 1 ; 1a
DEF OBJECT_MOVEMENT_BYTE_INDEX rb 1 ; 1b
DEF OBJECT_1C                  rb 1 ; 1c
DEF OBJECT_1D                  rb 1 ; 1d
DEF OBJECT_1E                  rb 1 ; 1e
DEF OBJECT_1F                  rb 1 ; 1f
DEF OBJECT_RANGE               rb 1 ; 20
DEF OBJECT_DATA                rb 7 ; 21
DEF OBJECT_LENGTH EQU _RS
DEF NUM_OBJECT_STRUCTS EQU 10

	rsreset
DEF CMDQUEUE_UNK0 rb 16
DEF CMDQUEUE_ENTRY_SIZE EQU _RS

	rsreset
DEF MAPOBJECT_OBJECT_STRUCT_ID rb 1 ; 0
DEF MAPOBJECT_SPRITE           rb 1 ; 1
DEF MAPOBJECT_Y_COORD          rb 1 ; 2
DEF MAPOBJECT_X_COORD          rb 1 ; 3
DEF MAPOBJECT_MOVEMENT         rb 1 ; 4
DEF MAPOBJECT_RADIUS           rb 1 ; 5
DEF MAPOBJECT_HOUR             rb 1 ; 6
DEF MAPOBJECT_TIMEOFDAY        rb 1 ; 7
DEF MAPOBJECT_COLOR            rb 1 ; 8
DEF MAPOBJECT_RANGE            rb 1 ; 9
DEF MAPOBJECT_SCRIPT_POINTER   rb 1 ; a
DEF MAPOBJECT_POINTER_HI       rb 1 ; b
DEF MAPOBJECT_EVENT_FLAG       rw 1
DEF MAPOBJECT_E                rb 1 ; unused
DEF MAPOBJECT_F                rb 1 ; unused
DEF MAP_OBJECT_LENGTH EQU _RS

	rsreset
DEF MAPOBJECTTEMPLATE_SPRITE           rb 1 ; 0
DEF MAPOBJECTTEMPLATE_Y_COORD          rb 1 ; 1
DEF MAPOBJECTTEMPLATE_X_COORD          rb 1 ; 2
DEF MAPOBJECTTEMPLATE_MOVEMENT         rb 1 ; 3
DEF MAPOBJECTTEMPLATE_RADIUS           rb 1 ; 4
DEF MAPOBJECTTEMPLATE_HOUR             rb 1 ; 5
DEF MAPOBJECTTEMPLATE_TIMEOFDAY        rb 1 ; 6
DEF MAPOBJECTTEMPLATE_COLOR            rb 1 ; 7
DEF MAPOBJECTTEMPLATE_RANGE            rb 1 ; 8
DEF MAPOBJECTTEMPLATE_SCRIPT_POINTER   rb 1 ; 9
DEF MAPOBJECTTEMPLATE_POINTER_HI       rb 1 ; a
DEF MAPOBJECTTEMPLATE_EVENT_FLAG       rw 1 ; b
DEF MAP_OBJECT_TEMPLATE_LENGTH EQU _RS

DEF PLAYER_OBJECT_INDEX    EQU 1
DEF COMPANION_OBJECT_INDEX EQU 2
