DEF MINIGAME_STARTING_COINS    EQU 256
DEF MINIGAME_END_LOOP_F EQU 7

DEF SLOTS_NO_BIAS        EQU -1
DEF SLOTS_NO_MATCH       EQU -1

DEF SLOTS_GFX_BLANK_TILE          EQU $17
DEF SLOTS_GFX_ILLUMINATED_LIGHT   EQU $14
DEF SLOTS_GFX_DEILLUMINATED_LIGHT EQU $23
DEF SLOTS_GFX_SEVEN_TILE_1        EQU $25
DEF SLOTS_GFX_SEVEN_TILE_2        EQU $41

DEF SLOTS_SEVEN    EQU $00
DEF SLOTS_POKEBALL EQU $04
DEF SLOTS_CHERRY   EQU $08
DEF SLOTS_PIKACHU  EQU $0c
DEF SLOTS_SQUIRTLE EQU $10
DEF SLOTS_STARYU   EQU $14

DEF REEL_SIZE EQU 15

; SlotsJumptable constants
	const_def
	const SLOTS_INIT
	const SLOTS_BET_AND_START
	const SLOTS_WAIT_START
	const SLOTS_WAIT_REEL1
	const SLOTS_WAIT_STOP_REEL1
	const SLOTS_WAIT_REEL2
	const SLOTS_WAIT_STOP_REEL2
	const SLOTS_WAIT_REEL3
	const SLOTS_WAIT_STOP_REEL3
	const SLOTS_NEXT_09
	const SLOTS_NEXT_0A
	const SLOTS_NEXT_0B
	const SLOTS_FLASH_IF_WIN
	const SLOTS_FLASH_SCREEN
	const SLOTS_GIVE_EARNED_COINS
	const SLOTS_PAYOUT_TEXT_AND_ANIM
	const SLOTS_PAYOUT_ANIM
	const SLOTS_RESTART_OR_QUIT
	const SLOTS_QUIT

; ReelActionJumptable constants
	const_def
	const REEL_ACTION_DO_NOTHING
	const REEL_ACTION_STOP_REEL_IGNORE_JOYPAD
	const REEL_ACTION_QUADRUPLE_RATE
	const REEL_ACTION_DOUBLE_RATE
	const REEL_ACTION_NORMAL_RATE
	const REEL_ACTION_HALF_RATE
	const REEL_ACTION_QUARTER_RATE
	const REEL_ACTION_STOP_REEL1
	const REEL_ACTION_STOP_REEL2
	const REEL_ACTION_STOP_REEL3
	const REEL_ACTION_SET_UP_REEL2_SKIP_TO_7
	const REEL_ACTION_WAIT_REEL2_SKIP_TO_7
	const REEL_ACTION_FAST_SPIN_REEL2_UNTIL_LINED_UP_7S
	const REEL_ACTION_0D
	const REEL_ACTION_CHECK_DROP_REEL
	const REEL_ACTION_WAIT_DROP_REEL
	const REEL_ACTION_START_SLOW_ADVANCE_REEL3
	const REEL_ACTION_WAIT_SLOW_ADVANCE_REEL3
	const REEL_ACTION_INIT_GOLEM
	const REEL_ACTION_WAIT_GOLEM
	const REEL_ACTION_END_GOLEM
	const REEL_ACTION_INIT_CHANSEY
	const REEL_ACTION_WAIT_CHANSEY
	const REEL_ACTION_WAIT_EGG
	const REEL_ACTION_DROP_REEL

; Constants for slot_reel offsets (see macros/wram.asm)
DEF REEL_ACTION        EQUS "(wReel1ReelAction - wReel1)"
DEF REEL_TILEMAP_ADDR  EQUS "(wReel1TilemapAddr - wReel1)"
DEF REEL_POSITION      EQUS "(wReel1Position - wReel1)"
DEF REEL_SPIN_DISTANCE EQUS "(wReel1SpinDistance - wReel1)"
DEF REEL_SPIN_RATE     EQUS "(wReel1SpinRate - wReel1)"
DEF REEL_OAM_ADDR      EQUS "(wReel1OAMAddr - wReel1)"
DEF REEL_X_COORD       EQUS "(wReel1XCoord - wReel1)"
DEF REEL_MANIP_COUNTER EQUS "(wReel1ManipCounter - wReel1)"
DEF REEL_MANIP_DELAY   EQUS "(wReel1ManipDelay - wReel1)"
DEF REEL_FIELD_0B      EQUS "(wReel1Field0b - wReel1)"
DEF REEL_STOP_DELAY    EQUS "(wReel1StopDelay - wReel1)"

; MinigamePikachuDoMovement.Jumptable constants
	const_def
	const MINIGAME_PIKACHU_INIT    ; 00
	const MINIGAME_PIKACHU_CONTROL ; 01
	const MINIGAME_PIKACHU_JUMPING ; 02
	const MINIGAME_PIKACHU_FALLING ; 03

; PikachuMiniGame_PerformGameFunction.Jumptable constants
	const_def
	const PIKACHU_MINIGAME_SETUP                ; 00
	const PIKACHU_MINIGAME_NOTE_SPAWNER         ; 01
	const PIKACHU_MINIGAME_SET_NEXT_SCENE_TIMER ; 02
	const PIKACHU_MINIGAME_WAIT_AND_GOTO_NEXT   ; 03
	const PIKACHU_MINIGAME_SHOW_JIGGLYPUFF      ; 04
	const PIKACHU_MINIGAME_FADE_OUT             ; 05


; PicrossSprites constants
	const_def
	const PATTERN_NORMAL
	const PATTERN_TILESET

; PicrossMinigame.Jumptable constants
	const_def
	const PICROSS_INIT_MODE
	const PICROSS_RUN_MODE
	const PICROSS_EXIT_MODE

; wPicrossCurrentCellType constants
	const_def
	const PICROSS_BLANK_CELL
	const PICROSS_COLORED_CELL
	const PICROSS_MARKED_CELL

DEF PICROSS_GFX_BGTILE EQU $80
DEF PICROSS_GFX_BUSHTILE EQU $81
DEF PICROSS_GFX_BUSHGROUNDTILE EQU $82
DEF PICROSS_GFX_GROUNDTILE EQU $83

DEF PICROSS_GFX_COLUMNS EQU $84
DEF PICROSS_GFX_ROWS EQU $b4
DEF PICROSS_GFX_TABLESTART equ $f0

; MemoryMinigame.Jumptable indices
	const_def
	const MEMORYGAME_RESTART_GAME
	const MEMORYGAME_RESTART_BOARD
	const MEMORYGAME_INIT_BOARD_AND_CURSOR
	const MEMORYGAME_CHECK_TRIES_REMAINING
	const MEMORYGAME_PICK_CARD_1
	const MEMORYGAME_PICK_CARD_2
	const MEMORYGAME_DELAY_PICK_AGAIN
	const MEMORYGAME_REVEAL_ALL
	const MEMORYGAME_ASK_PLAY_AGAIN

; FifteenPuzzleMinigame.Jumptable indices
	const_def
	const FIFTEENPUZZLE_DOING_PUZZLE
	const FIFTEENPUZZLE_SOLVED_PUZZLE
	const FIFTEENPUZZLE_SLIDE_FINAL_PANEL
	const FIFTEENPUZZLE_SLIDE_PUZZLE_LEFT
	const FIFTEENPUZZLE_END_SCREEN

DEF FIFTEENPUZZLE_PANEL_COUNT EQU 16
DEF FIFTEENPUZZLE_EMPTY_PANEL_NUM EQU FIFTEENPUZZLE_PANEL_COUNT - 1

; PokerMinigame.Jumptable indices
	const_def
	const POKER_INIT
	const POKER_START_WAIT
	const POKER_START
	const POKER_CHANGE_INIT
	const POKER_CHANGE
	const POKER_CHANGE_CARD
	const POKER_COIN_HIT
	const POKER_DOUBLE_UP_CHECK
	const POKER_DOUBLE_UP_INIT
	const POKER_DOUBLE_UP
	const POKER_PAYOUT_INIT
	const POKER_PAYOUT
	const POKER_RETRY_SCREEN
	const POKER_EXIT
	
; PokerMinigame Payouts
	const_def
	const POKER_PAYOUT_DUD
	const POKER_PAYOUT_ONEPAIR
	const POKER_PAYOUT_TWOPAIR
	const POKER_PAYOUT_THREEOFAKIND
	const POKER_PAYOUT_STRAIGHT
	const POKER_PAYOUT_FLUSH
	const POKER_PAYOUT_FULL_HOUSE
	const POKER_PAYOUT_STRAIGHT_FLUSH
	const POKER_PAYOUT_FOUROFAKIND
	const POKER_PAYOUT_FIVEOFAKIND
	
DEF POKER_MAX_CARDS EQU 10 * 5
