	const_def
	const FACE_DOWN         ; $00
	const FACE_UP           ; $01
	const FACE_LEFT         ; $02
	const FACE_RIGHT        ; $03
	const SLOW_STEP_DOWN    ; $04
	const SLOW_STEP_UP      ; $05
	const SLOW_STEP_LEFT    ; $06
	const SLOW_STEP_RIGHT   ; $07
	const STEP_DOWN         ; $08
	const STEP_UP           ; $09
	const STEP_LEFT         ; $0a
	const STEP_RIGHT        ; $0b
	const FAST_STEP_DOWN    ; $0c
	const FAST_STEP_UP      ; $0d
	const FAST_STEP_LEFT    ; $0e
	const FAST_STEP_RIGHT   ; $0f
	const FAST_STEP_DOWN2   ; $10
	const FAST_STEP_UP2     ; $11
	const FAST_STEP_LEFT2   ; $12
	const FAST_STEP_RIGHT2  ; $13
	const SLOW_JUMP_DOWN    ; $14
	const SLOW_JUMP_UP      ; $15
	const SLOW_JUMP_LEFT    ; $16
	const SLOW_JUMP_RIGHT   ; $17
	const JUMP_DOWN         ; $18
	const JUMP_UP           ; $19
	const JUMP_LEFT         ; $1a
	const JUMP_RIGHT        ; $1b
	const FAST_JUMP_DOWN    ; $1c
	const FAST_JUMP_UP      ; $1d
	const FAST_JUMP_LEFT    ; $1e
	const FAST_JUMP_RIGHT   ; $1f
	const FAST_JUMP_DOWN2   ; $20
	const FAST_JUMP_UP2     ; $21
	const FAST_JUMP_LEFT2   ; $22
	const FAST_JUMP_RIGHT2  ; $23
	const MOVEMENT_24       ; $24
	const MOVEMENT_25       ; $25
	const MOVEMENT_26       ; $26
	const MOVEMENT_27       ; $27
	const MOVEMENT_28       ; $28
	const MOVEMENT_29       ; $29
	const NO_MOVEMENT       ; $2a
