	const_def
	const FACE_DOWN          ; $00
	const FACE_UP            ; $01
	const FACE_LEFT          ; $02
	const FACE_RIGHT         ; $03
	const SLOW_STEP_DOWN     ; $04
	const SLOW_STEP_UP       ; $05
	const SLOW_STEP_LEFT     ; $06
	const SLOW_STEP_RIGHT    ; $07
	const STEP_DOWN          ; $08
	const STEP_UP            ; $09
	const STEP_LEFT          ; $0a
	const STEP_RIGHT         ; $0b
	const FAST_STEP_DOWN     ; $0c
	const FAST_STEP_UP       ; $0d
	const FAST_STEP_LEFT     ; $0e
	const FAST_STEP_RIGHT    ; $0f
	const FASTEST_STEP_DOWN  ; $10
	const FASTEST_STEP_UP    ; $11
	const FASTEST_STEP_LEFT  ; $12
	const FASTEST_STEP_RIGHT ; $13
	const SLOW_JUMP_DOWN     ; $14
	const SLOW_JUMP_UP       ; $15
	const SLOW_JUMP_LEFT     ; $16
	const SLOW_JUMP_RIGHT    ; $17
	const JUMP_DOWN          ; $18
	const JUMP_UP            ; $19
	const JUMP_LEFT          ; $1a
	const JUMP_RIGHT         ; $1b
	const FAST_JUMP_DOWN     ; $1c
	const FAST_JUMP_UP       ; $1d
	const FAST_JUMP_LEFT     ; $1e
	const FAST_JUMP_RIGHT    ; $1f
	const FASTEST_JUMP_DOWN  ; $20
	const FASTEST_JUMP_UP    ; $21
	const FASTEST_JUMP_LEFT  ; $22
	const FASTEST_JUMP_RIGHT ; $23
	const MOVEMENT_24        ; $24
	const MOVEMENT_25        ; $25
	const MOVEMENT_26        ; $26
	const MOVEMENT_27        ; $27
	const MOVEMENT_28        ; $28
	const MOVEMENT_29        ; $29
	const NO_MOVEMENT        ; $2a
	const MOVEMENT_2B        ; $2b
	const MOVEMENT_2C        ; $2c
	const MOVEMENT_2D        ; $2d
	const MOVEMENT_2E        ; $2e
	const MOVEMENT_2F        ; $2f
	const MOVEMENT_30        ; $30
	const MOVEMENT_31        ; $31
	const MOVEMENT_32        ; $32
	const MOVEMENT_33        ; $33
