	const_def
	const PAL_TOWN_00 ; 00
	const PAL_TOWN_01 ; 01
	const PAL_TOWN_02 ; 02
	const PAL_TOWN_03 ; 03
	const PAL_TOWN_04 ; 04
	const PAL_TOWN_05 ; 05
	const PAL_TOWN_06 ; 06
	const PAL_TOWN_07 ; 07
	const PAL_TOWN_08 ; 08
	const PAL_TOWN_09 ; 09
	const PAL_TOWN_0A ; 0a
	const PAL_TOWN_0B ; 0b
	const PAL_TOWN_0C ; 0c
	const PAL_TOWN_0D ; 0d
	const PAL_BLACK ; 0e
	const PAL_MEWMON ; 0f
	const PAL_BLUEMON ; 10
	const PAL_REDMON ; 11
	const PAL_CYANMON ; 12
	const PAL_PURPLEMON ; 13
	const PAL_BROWNMON ; 14
	const PAL_GREENMON ; 15
	const PAL_PINKMON ; 16
	const PAL_YELLOWMON ; 17
	const PAL_GREYMON ; 18
	const PAL_DARKMEWMON ; 19
	const PAL_DARKBLUEMON ; 1a
	const PAL_DARKREDMON ; 1b
	const PAL_DARKCYANMON ; 1c
	const PAL_DARKPURPLEMON ; 1d
	const PAL_DARKBROWNMON ; 1e
	const PAL_TANMON ; 1f
	const PAL_BLUEPINKMON ; 20
	const PAL_ORANGEMON ; 21
	const PAL_DARKGREYMON ; 22
	const PAL_GREENBAR ; 23
	const PAL_YELLOWBAR ; 24
	const PAL_REDBAR ; 25
	const PAL_TOWN_MAP ; 26
	const PAL_LOGO_1 ; 27
	const PAL_LOGO_2 ; 28
	const PAL_GAME_FREAK ; 29
	const PAL_INTRO_WATER ; 2a
	const PAL_INTRO_LAPRAS ; 2b
	const PAL_INTRO_FOREST ; 2c
	const PAL_INTRO_PURIN_PIKACHU ; 2d
	const PAL_INTRO_KAMEX ; 2e
	const PAL_INTRO_FUSHIGIBANA ; 2f
	const PAL_INTRO_LIZARDON ; 30
	const PAL_SLOTS_1 ; 31
	const PAL_SLOTS_2 ; 32
	const PAL_SLOTS_3 ; 33
	const PAL_SLOTS_4 ; 34
	const PAL_POKER_1 ; 35
	const PAL_POKER_2 ; 36
	const PAL_POKER_3 ; 37
	const PAL_POKER_4 ; 38
	const PAL_39 ; 39
