; SuperPalettes indexes (see data/sgb/super_palettes.inc)
	const_def
	const PAL_ROUTE ; 00
	const PAL_TOWN_NORTH ; 01
	const PAL_TOWN_STAND ; 02
	const PAL_TOWN_WEST ; 03
	const PAL_TOWN_NEWTYPE ; 04
	const PAL_TOWN_SUGAR ; 05
	const PAL_TOWN_FONTO ; 06
	const PAL_TOWN_SILENTHILL ; 07
	const PAL_TOWN_HAITEKU ; 08
	const PAL_TOWN_SOUTH ; 09
	const PAL_TOWN_BULL ; 0a
	const PAL_TOWN_BAADON ; 0b
	const PAL_TOWN_OLDCITY ; 0c
	const PAL_NIGHTTIME ; 0d
	const PAL_BLACK ; 0e
	const PAL_MEWMON ; 0f
	const PAL_BLUEMON ; 10
	const PAL_REDMON ; 11
	const PAL_CYANMON ; 12
	const PAL_PURPLEMON ; 13
	const PAL_BROWNMON ; 14
	const PAL_GREENMON ; 15
	const PAL_PINKMON ; 16
	const PAL_YELLOWMON ; 17
	const PAL_GRAYMON ; 18
	const PAL_SHINY_MEWMON ; 19
	const PAL_SHINY_BLUEMON ; 1a
	const PAL_SHINY_REDMON ; 1b
	const PAL_SHINY_CYANMON ; 1c
	const PAL_SHINY_PURPLEMON ; 1d
	const PAL_SHINY_BROWNMON ; 1e
	const PAL_SHINY_GREENMON ; 1f
	const PAL_SHINY_PINKMON ; 20
	const PAL_SHINY_YELLOWMON ; 21
	const PAL_SHINY_GRAYMON ; 22
	const PAL_GREEN_BAR ; 23
	const PAL_YELLOW_BAR ; 24
	const PAL_RED_BAR ; 25
	const PAL_TOWN_MAP ; 26
	const PAL_LOGO_1 ; 27
	const PAL_LOGO_2 ; 28
	const PAL_GAME_FREAK ; 29
	const PAL_INTRO_WATER ; 2a
	const PAL_INTRO_LAPRAS ; 2b
	const PAL_INTRO_FOREST ; 2c
	const PAL_INTRO_JIGGLYPUFF_PIKACHU ; 2d
	const PAL_INTRO_BLASTOISE ; 2e
	const PAL_INTRO_VENUSAUR ; 2f
	const PAL_INTRO_CHARIZARD ; 30
	const PAL_SLOTS_1 ; 31
	const PAL_SLOTS_2 ; 32
	const PAL_SLOTS_3 ; 33
	const PAL_SLOTS_4 ; 34
	const PAL_POKER_1 ; 35
	const PAL_POKER_2 ; 36
	const PAL_POKER_3 ; 37
	const PAL_POKER_4 ; 38
	const PAL_RADIO ; 39
