DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_GOLD)
DEF PLAYERNAME1 EQUS "ゴールド"
DEF PLAYERNAME2 EQUS "サトシ"
DEF PLAYERNAME3 EQUS "ジャック"

DEF RIVALNAME1 EQUS "シルバー"
DEF RIVALNAME2 EQUS "シゲル"
DEF RIVALNAME3 EQUS "ジョン"
ELIF DEF(_SILVER)
DEF PLAYERNAME1 EQUS "シルバー"
DEF PLAYERNAME2 EQUS "シゲル"
DEF PLAYERNAME3 EQUS "ジョン"

DEF RIVALNAME1 EQUS "ゴールド"
DEF RIVALNAME2 EQUS "サトシ"
DEF RIVALNAME3 EQUS "ジャック"
ENDC

DEF MOMNAME1 EQUS "おかあさん"
DEF MOMNAME2 EQUS "ママ"
DEF MOMNAME3 EQUS "かあちゃん"
