; old RBY index numbers
; used primarily for cries
	const_def 1
	const MON_SIDON        ; $01
	const MON_GARURA       ; $02
	const MON_NIDORAN_M    ; $03
	const MON_PIPPI        ; $04
	const MON_ONISUZUME    ; $05
	const MON_BIRIRIDAMA   ; $06
	const MON_NIDOKING     ; $07
	const MON_YADORAN      ; $08
	const MON_FUSHIGISOU   ; $09
	const MON_NASSY        ; $0A
	const MON_BERORINGA    ; $0B
	const MON_TAMATAMA     ; $0C
	const MON_BETBETER     ; $0D
	const MON_GANGAR       ; $0E
	const MON_NIDORAN_F    ; $0F
	const MON_NIDOQUEEN    ; $10
	const MON_KARAKARA     ; $11
	const MON_SIHORN       ; $12
	const MON_LAPLACE      ; $13
	const MON_WINDIE       ; $14
	const MON_MEW          ; $15
	const MON_GYARADOS     ; $16
	const MON_SHELLDER     ; $17
	const MON_MENOKURAGE   ; $18
	const MON_GHOS         ; $19
	const MON_STRIKE       ; $1A
	const MON_HITODEMAN    ; $1B
	const MON_KAMEX        ; $1C
	const MON_KAILIOS      ; $1D
	const MON_MONJARA      ; $1E
	const MON_KAPOERER     ; $1F
	const MON_PUDIE        ; $20
	const MON_GARDIE       ; $21
	const MON_IWARK        ; $22
	const MON_ONIDRILL     ; $23
	const MON_POPPO        ; $24
	const MON_YADON        ; $25
	const MON_YUNGERER     ; $26
	const MON_GOLONE       ; $27
	const MON_LUCKY        ; $28
	const MON_GORIKY       ; $29
	const MON_BARRIERD     ; $2A
	const MON_SAWAMULAR    ; $2B
	const MON_EBIWALAR     ; $2C
	const MON_ARBOK        ; $2D
	const MON_PARASECT     ; $2E
	const MON_KODUCK       ; $2F
	const MON_SLEEPE       ; $30
	const MON_GOLONYA      ; $31
	const MON_HANEKO       ; $32
	const MON_BOOBER       ; $33
	const MON_TAIL         ; $34
	const MON_ELEBOO       ; $35
	const MON_RARECOIL     ; $36
	const MON_DOGARS       ; $37
	const MON_POPONEKO     ; $38
	const MON_MANKEY       ; $39
	const MON_PAWOU        ; $3A
	const MON_DIGDA        ; $3B
	const MON_KENTAUROS    ; $3C
	const MON_WATANEKO     ; $3D
	const MON_BARIRINA     ; $3E
	const MON_LIP          ; $3F
	const MON_KAMONEGI     ; $40
	const MON_KONGPANG     ; $41
	const MON_KAIRYU       ; $42
	const MON_ELEBABY      ; $43
	const MON_BOOBY        ; $44
	const MON_KIREIHANA    ; $45
	const MON_DODO         ; $46
	const MON_NYOROMO      ; $47
	const MON_ROUGELA      ; $48
	const MON_FIRE         ; $49
	const MON_FREEZER      ; $4A
	const MON_THUNDER      ; $4B
	const MON_METAMON      ; $4C
	const MON_NYARTH       ; $4D
	const MON_CRAB         ; $4E
	const MON_TSUBOMITTO   ; $4F
	const MON_MILTANK      ; $50
	const MON_BOMBSEEKER   ; $51
	const MON_ROKON        ; $52
	const MON_KYUKON       ; $53
	const MON_PIKACHU      ; $54
	const MON_RAICHU       ; $55
	const MON_GIFT         ; $56
	const MON_KOTORA       ; $57
	const MON_MINIRYU      ; $58
	const MON_HAKURYU      ; $59
	const MON_KABUTO       ; $5A
	const MON_KABUTOPS     ; $5B
	const MON_TATTU        ; $5C
	const MON_SEADRA       ; $5D
	const MON_RAITORA      ; $5E
	const MON_MADAME       ; $5F
	const MON_SAND         ; $60
	const MON_SANDPAN      ; $61
	const MON_OMNITE       ; $62
	const MON_OMSTAR       ; $63
	const MON_PURIN        ; $64
	const MON_PUKURIN      ; $65
	const MON_EIEVUI       ; $66
	const MON_BOOSTER      ; $67
	const MON_THUNDERS     ; $68
	const MON_SHOWERS      ; $69
	const MON_WANRIKY      ; $6A
	const MON_ZUBAT        ; $6B
	const MON_ARBO         ; $6C
	const MON_PARAS        ; $6D
	const MON_NYOROZO      ; $6E
	const MON_NYOROBON     ; $6F
	const MON_BEEDLE       ; $70
	const MON_COCOON       ; $71
	const MON_SPEAR        ; $72
	const MON_NOROWARA     ; $73
	const MON_DODORIO      ; $74
	const MON_OKORIZARU    ; $75
	const MON_DUGTRIO      ; $76
	const MON_MORPHON      ; $77
	const MON_JUGON        ; $78
	const MON_KYONPAN      ; $79
	const MON_YAMIKARASU   ; $7A
	const MON_CATERPIE     ; $7B
	const MON_TRANSEL      ; $7C
	const MON_BUTTERFREE   ; $7D
	const MON_KAIRIKY      ; $7E
	const MON_HAPPI        ; $7F
	const MON_GOLDUCK      ; $80
	const MON_SLEEPER      ; $81
	const MON_GOLBAT       ; $82
	const MON_MEWTWO       ; $83
	const MON_KABIGON      ; $84
	const MON_KOIKING      ; $85
	const MON_SCISSORS     ; $86
	const MON_PURAKKUSU    ; $87
	const MON_BETBETON     ; $88
	const MON_DEVIL        ; $89
	const MON_KINGLER      ; $8A
	const MON_PARSHEN      ; $8B
	const MON_HELGAA       ; $8C
	const MON_MARUMINE     ; $8D
	const MON_PIXY         ; $8E
	const MON_MATADOGAS    ; $8F
	const MON_PERSIAN      ; $90
	const MON_GARAGARA     ; $91
	const MON_WOLFMAN      ; $92
	const MON_GHOST        ; $93
	const MON_CASEY        ; $94
	const MON_FOODIN       ; $95
	const MON_PIGEON       ; $96
	const MON_PIGEOT       ; $97
	const MON_STARMIE      ; $98
	const MON_FUSHIGIDANE  ; $99
	const MON_FUSHIGIBANA  ; $9A
	const MON_DOKUKURAGE   ; $9B
	const MON_WARWOLF      ; $9C
	const MON_TOSAKINTO    ; $9D
	const MON_AZUMAO       ; $9E
	const MON_PORYGON2     ; $9F
	const MON_NAMEIL       ; $A0
	const MON_HAGANEIL     ; $A1
	const MON_KINGDRA      ; $A2
	const MON_PONYTA       ; $A3
	const MON_GALLOP       ; $A4
	const MON_KORATTA      ; $A5
	const MON_RATTA        ; $A6
	const MON_NIDORINO     ; $A7
	const MON_NIDORINA     ; $A8
; LEAFY isn't in table at 10:4B70
; and its ID 0xFB will be found at
; 10:4117 (index 0x4A7 + 1 % 0x100 = 0xA8)
MON_LEAFY EQU const_value + -1
	const MON_ISITSUBUTE   ; $A9
	const MON_PORYGON      ; $AA
	const MON_PTERA        ; $AB
	const MON_RAI          ; $AC
	const MON_COIL         ; $AD
	const MON_EN           ; $AE
	const MON_SUI          ; $AF
	const MON_HITOKAGE     ; $B0
	const MON_ZENIGAME     ; $B1
	const MON_LIZARDO      ; $B2
	const MON_KAMEIL       ; $B3
	const MON_LIZARDON     ; $B4
	const MON_NYULA        ; $B5
	const MON_HOUOU        ; $B6
	const MON_TOGEPY       ; $B7
	const MON_BULU         ; $B8
	const MON_NAZONOKUSA   ; $B9
	const MON_KUSAIHANA    ; $BA
	const MON_RUFFRESIA    ; $BB
	const MON_MADATSUBOMI  ; $BC
	const MON_UTSUDON      ; $BD
	const MON_UTSUBOT      ; $BE
	const MON_HAPPA        ; $BF
	const MON_HANAMOGURA   ; $C0
	const MON_HANARYU      ; $C1
	const MON_HONOGUMA     ; $C2
	const MON_VOLBEAR      ; $C3
	const MON_DYNABEAR     ; $C4
	const MON_KURUSU       ; $C5
	const MON_AQUA         ; $C6
	const MON_AQUARIA      ; $C7
	const MON_HOHO         ; $C8
	const MON_BOBO         ; $C9
	const MON_PACHIMEE     ; $CA
	const MON_MOKOKO       ; $CB
	const MON_DENRYU       ; $CC
	const MON_MIKON        ; $CD
	const MON_MONJA        ; $CE
	const MON_JARANRA      ; $CF
	const MON_HANEEI       ; $D0
	const MON_PUKU         ; $D1
	const MON_SHIBIREFUGU  ; $D2
	const MON_PICHU        ; $D3
	const MON_PY           ; $D4
	const MON_PUPURIN      ; $D5
	const MON_MIZUUO       ; $D6
	const MON_NATY         ; $D7
	const MON_NATIO        ; $D8
	const MON_GYOPIN       ; $D9
	const MON_MARIL        ; $DA
	const MON_MANBO1       ; $DB
	const MON_IKARI        ; $DC
	const MON_GROTESS      ; $DD
	const MON_EKSING       ; $DE
	const MON_PARA         ; $DF
	const MON_KOKUMO       ; $E0
	const MON_TWOHEAD      ; $E1
	const MON_YOROIDORI    ; $E2
	const MON_ANIMON       ; $E3
	const MON_HINAZU       ; $E4
	const MON_SUNNY        ; $E5
	const MON_PAON         ; $E6
	const MON_DONPHAN      ; $E7
	const MON_TWINZ        ; $E8
	const MON_KIRINRIKI    ; $E9
	const MON_PAINTER      ; $EA
	const MON_KOUNYA       ; $EB
	const MON_RINRIN       ; $EC
	const MON_BERURUN      ; $ED
	const MON_NYOROTONO    ; $EE
	const MON_YADOKING     ; $EF
	const MON_ANNON        ; $F0
	const MON_REDIBA       ; $F1
	const MON_MITSUBOSHI   ; $F2
	const MON_PUCHICORN    ; $F3
	const MON_EIFIE        ; $F4
	const MON_BLACKY       ; $F5
	const MON_TURBAN       ; $F6
	const MON_BETBABY      ; $F7
	const MON_TEPPOUO      ; $F8
	const MON_OKUTANK      ; $F9
	const MON_GONGU        ; $FA
