; wSpriteAnimDict keys
	const_def
	const SPRITE_ANIM_DICT_DEFAULT      ; 0
	const SPRITE_ANIM_DICT_GS_INTRO     ; 1
	const SPRITE_ANIM_DICT_GS_INTRO_2   ; 2
	const_skip 2                        ; unused
	const SPRITE_ANIM_DICT_TEXT_CURSOR  ; 5
	const SPRITE_ANIM_DICT_GS_SPLASH    ; 6
	const SPRITE_ANIM_DICT_SLOTS        ; 7
	const SPRITE_ANIM_DICT_ARROW_CURSOR ; 8
; wSpriteAnimDict size (see ram/wram.asm)
NUM_SPRITEANIMDICT_ENTRIES EQU 10

; SpriteAnimSeqData indexes
SPRITE_ANIM_INDEX_08                            EQU $08

SPRITE_ANIM_INDEX_GS_INTRO_BUBBLE               EQU $21
SPRITE_ANIM_INDEX_GS_INTRO_OMANYTE              EQU $22
SPRITE_ANIM_INDEX_GS_INTRO_MAGIKARP             EQU $23
SPRITE_ANIM_INDEX_UNUSED_INTRO_AERODACTYL       EQU $24
SPRITE_ANIM_INDEX_GS_INTRO_LAPRAS               EQU $25
SPRITE_ANIM_INDEX_GS_INTRO_NOTE                 EQU $26
SPRITE_ANIM_INDEX_GS_INTRO_SMALLER_NOTE         EQU $27
SPRITE_ANIM_INDEX_GS_INTRO_JIGGLYPUFF           EQU $28
SPRITE_ANIM_INDEX_GS_INTRO_PIKACHU              EQU $29
SPRITE_ANIM_INDEX_GS_INTRO_PIKACHU_TAIL         EQU $2a
SPRITE_ANIM_INDEX_GS_INTRO_FIREBALL             EQU $2b
SPRITE_ANIM_INDEX_GS_INTRO_BLASTOISE            EQU $2c
SPRITE_ANIM_INDEX_GS_INTRO_VENUSAUR             EQU $2d

SPRITE_ANIM_INDEX_GS_TITLE_FLAME_NOTE           EQU $2e

SPRITE_ANIM_INDEX_39                            EQU $39
SPRITE_ANIM_INDEX_GAMEFREAK_LOGO                EQU $3a
SPRITE_ANIM_INDEX_GS_INTRO_STAR                 EQU $3b
SPRITE_ANIM_INDEX_GS_INTRO_SPARKLE              EQU $3c
SPRITE_ANIM_INDEX_40                            EQU $40
SPRITE_ANIM_INDEX_41                            EQU $41
SPRITE_ANIM_INDEX_44                            EQU $44
SPRITE_ANIM_INDEX_4B                            EQU $4b
