; name lengths
DEF NAME_LENGTH          EQU 11 ; English
DEF PLAYER_NAME_LENGTH   EQU 6 ; Japanese
DEF BOX_NAME_LENGTH      EQU 9
DEF MON_NAME_LENGTH      EQU 6
DEF TYPE_NAME_LENGTH     EQU 5
DEF MOVE_NAME_LENGTH     EQU 8
DEF ITEM_NAME_LENGTH     EQU 11
DEF TRAINER_CLASS_NAME_LENGTH EQU 11

; GetName types (see home/names.asm)
	const_def 1
	const MON_NAME              ; 01
	const MOVE_NAME             ; 02
	const DUMMY_NAME            ; 03
	const ITEM_NAME             ; 04
	const PARTY_OT_NAME         ; 05
	const ENEMY_OT_NAME         ; 06
	const TRAINER_NAME          ; 07
	const MOVE_DESC_NAME_BROKEN ; 08

; see home/text.asm
DEF BORDER_WIDTH   EQU 2
DEF TEXTBOX_WIDTH  EQU SCREEN_WIDTH
DEF TEXTBOX_INNERW EQU TEXTBOX_WIDTH - BORDER_WIDTH
DEF TEXTBOX_HEIGHT EQU 6
DEF TEXTBOX_INNERH EQU TEXTBOX_HEIGHT - BORDER_WIDTH
DEF TEXTBOX_X      EQU 0
DEF TEXTBOX_INNERX EQU TEXTBOX_X + 1
DEF TEXTBOX_Y      EQU SCREEN_HEIGHT - TEXTBOX_HEIGHT
DEF TEXTBOX_INNERY EQU TEXTBOX_Y + 2

; PrintNumber bit flags (see home/print_num.asm)
	const_def 6
	shift_const PRINTNUM_LEFTALIGN    ; 6
	shift_const PRINTNUM_LEADINGZEROS ; 7

; character sets (see constants/charmap.asm)
DEF FIRST_REGULAR_TEXT_CHAR EQU $60
DEF FIRST_HIRAGANA_DAKUTEN_CHAR EQU $20
