; Tilesets indexes
; TODO: Temporary placeholders
	const_def
	const TILESET_SILENT_HILL
	const TILESET_OLD_CITY
	const TILESET_WEST
	const TILESET_HAITEKU
	const TILESET_BAADON
	const TILESET_FONTO
	const TILESET_BULL_FOREST
	const TILESET_KANTO
	const TILESET_SOUTH
	const TILESET_HOUSE
	const TILESET_LAB
	const TILESET_JAPANESE_HOUSE
	const TILESET_POKECENTER
	const TILESET_MART
	const TILESET_AQUARIUM
	const TILESET_TOWER
	const TILESET_BIG_MART
	const TILESET_ROUTE_GATE
	const TILESET_RADIO_TOWER
	const TILESET_ROCKET_HOUSE
	const TILESET_GYM
	const TILESET_OFFICE
	const TILESET_RUINS_OF_ALPH
	const TILESET_CAVE
	const TILESET_POWER_PLANT
	const TILESET_SS_ANNE
	const TILESET_SS_ANNE_DOCK
	const TILESET_FOREST
