SECTION "NULL", ROM0
NULL::

INCLUDE "home/rst.asm"
INCLUDE "home/interrupts.asm"
INCLUDE "home/header.asm"


SECTION "Home", ROM0

INCLUDE "home/vblank.asm"
INCLUDE "home/delay.asm"
INCLUDE "home/rtc.asm"
INCLUDE "home/fade.asm"
INCLUDE "home/lcd.asm"
INCLUDE "home/timer.asm"
INCLUDE "home/time.asm"
INCLUDE "home/init.asm"
INCLUDE "home/serial.asm"
INCLUDE "home/joypad.asm"
INCLUDE "home/sound_test.asm"
INCLUDE "home/pic.asm"
INCLUDE "home/copy2.asm"
INCLUDE "home/text.asm"
INCLUDE "home/vcopy.asm"
INCLUDE "home/map_objects.asm"
INCLUDE "home/movement.asm"
INCLUDE "home/menu_window.asm"
INCLUDE "home/menu.asm"
INCLUDE "home/window.asm"
INCLUDE "home/load_options.asm"
INCLUDE "home/toolgear.asm"
INCLUDE "home/map.asm"
INCLUDE "home/overworld.asm"
INCLUDE "home/tileset.asm"
INCLUDE "home/farcall.asm"
INCLUDE "home/predef.asm"
INCLUDE "home/talk_to_npc.asm"
INCLUDE "home/trainers.asm"
INCLUDE "home/item2.asm"
INCLUDE "home/random.asm"
INCLUDE "home/sram.asm"
INCLUDE "home/bankswitch.asm"
INCLUDE "home/item_amount.asm"
INCLUDE "home/text2.asm"
INCLUDE "home/math2.asm"
INCLUDE "home/clear_sprites.asm"
INCLUDE "home/copy.asm"
INCLUDE "home/math.asm"
INCLUDE "home/print_text.asm"
INCLUDE "home/util.asm"
INCLUDE "home/print_num.asm"
INCLUDE "home/print_hex.asm"
INCLUDE "home/jumptable.asm"
INCLUDE "home/queue_script.asm"
INCLUDE "home/tables.asm"
INCLUDE "home/tilemap.asm"
INCLUDE "home/give_item.asm"
INCLUDE "home/pokedex_flags.asm"
INCLUDE "home/names.asm"
INCLUDE "home/scrolling_menu.asm"
INCLUDE "home/std_scripts.asm"
INCLUDE "home/mon_stats.asm"
INCLUDE "home/cry.asm"
INCLUDE "home/pokemon.asm"
INCLUDE "home/nicknames.asm"
INCLUDE "home/print_bcd.asm"
INCLUDE "home/uncompress.asm"
INCLUDE "home/battle.asm"
INCLUDE "home/item.asm"
INCLUDE "home/battle_anims.asm"
INCLUDE "home/sprite_anims.asm"
INCLUDE "home/audio.asm"
