ROMS := pokegold-spaceworld.gb \
        pokesilver-spaceworld.gb \
        pokegold-spaceworld-debug.gb \
        pokesilver-spaceworld-debug.gb
CORRECTEDROMS := $(ROMS:%.gb=%-correctheader.gb)

DIRS := home engine data gfx audio maps scripts ram dumps garbage

BUILD := build

rwildcard = $(foreach d, $(wildcard $1*), $(filter $(subst *, %, $2), $d) $(call rwildcard, $d/, $2))
ASMFILES := $(call rwildcard, $(DIRS), *.asm) $(FILES)

pokegold-spaceworld_obj         := $(patsubst %.asm, $(BUILD)/%_gold.o, $(ASMFILES))
pokegold-spaceworld-debug_obj   := $(patsubst %.asm, $(BUILD)/%_gold_debug.o, $(ASMFILES))
pokesilver-spaceworld_obj       := $(patsubst %.asm, $(BUILD)/%_silver.o, $(ASMFILES))
pokesilver-spaceworld-debug_obj := $(patsubst %.asm, $(BUILD)/%_silver_debug.o, $(ASMFILES))


### Build tools

ifeq (,$(shell which sha1sum))
SHA1 := shasum
else
SHA1 := sha1sum
endif

PYTHON := python3

RGBDS ?=
RGBASM  ?= $(RGBDS)rgbasm
RGBFIX  ?= $(RGBDS)rgbfix
RGBGFX  ?= $(RGBDS)rgbgfx
RGBLINK ?= $(RGBDS)rgblink

RGBASMFLAGS  ?= -Weverything -Wtruncation=1
RGBLINKFLAGS ?= -Weverything -Wtruncation=1
RGBFIXFLAGS  ?= -Weverything
RGBGFXFLAGS  ?= -Weverything

tools/gfx :=


### Build targets

.SECONDEXPANSION:

.PHONY: \
	all \
	gold \
	silver \
	gold_debug \
	silver_debug \
	tools \
	clean \
	tidy \
	compare

all: $(ROMS) $(CORRECTEDROMS) compare
gold: pokegold-spaceworld.gb pokegold-spaceworld-correctheader.gb
silver: pokesilver-spaceworld.gb pokesilver-spaceworld-correctheader.gb
gold_debug: pokegold-spaceworld-debug.gb pokegold-spaceworld-debug-correctheader.gb
silver_debug: pokesilver-spaceworld-debug.gb pokesilver-spaceworld-debug-correctheader.gb

compare: $(ROMS) $(CORRECTEDROMS)
	@$(SHA1) -c roms.sha1

tools tools/pkmncompress tools/gfx tools/scan_includes:
	"$(MAKE)" -C tools/

# Remove files generated by the build process.
clean:
	rm -rf $(ROMS) $(CORRECTEDROMS) \
	       $(ROMS:.gb=.sym) $(CORRECTEDROMS:.gb=.sym) \
	       $(ROMS:.gb=.map) $(CORRECTEDROMS:.gb=.map) \
	       $(BUILD) rgbdscheck.o
	"$(MAKE)" -C tools clean

# Remove generated files except for graphics.
tidy:
	rm -rf $(ROMS) $(CORRECTEDROMS) \
	       $(ROMS:.gb=.sym) $(CORRECTEDROMS:.gb=.sym) \
	       $(ROMS:.gb=.map) $(CORRECTEDROMS:.gb=.map) \
	       $(pokegold-spaceworld_obj) $(pokesilver-spaceworld_obj) \
	       $(pokegold-spaceworld-debug_obj) $(pokesilver-spaceworld-debug_obj) \
	       rgbdscheck.o


### Build products

rgbdscheck.o: rgbdscheck.asm
	$(RGBASM) -o $@ $<

%.map: %.gb

%-correctheader.gb: RGBFIXFLAGS += -f hg -m MBC3+TIMER+RAM+BATTERY -Wno-overwrite
%-correctheader.gb: %.gb
	cp $< $@
	cp $(<:.gb=.sym) $(@:.gb=.sym)
	$(RGBFIX) $(RGBFIXFLAGS) $@

RGBLINKFLAGS += -d
RGBFIXFLAGS += -sf lh -k 01 -l 0x33 -m MBC1+RAM+BATTERY -r 3 -p 0xff

pokegold%.gb:   RGBFIXFLAGS += -t POKEMON2GOLD
pokesilver%.gb: RGBFIXFLAGS += -t POKEMON2SILVER

%.gb: $$(%_obj) layout.link
	$(RGBLINK) $(RGBLINKFLAGS) -l layout.link -m $*.map -n $*.sym -o $@ $(filter %.o,$^)
	$(RGBFIX) $(RGBFIXFLAGS) $@


### Misc file-specific graphics rules

include gfx/gfx.mk


### Catch-all build target rules

RGBASMFLAGS += -E -i $(BUILD)/

$(pokegold-spaceworld_obj):         RGBASMFLAGS += -D _GOLD
$(pokesilver-spaceworld_obj):       RGBASMFLAGS += -D _SILVER
$(pokegold-spaceworld-debug_obj):   RGBASMFLAGS += -D _GOLD -D _DEBUG
$(pokesilver-spaceworld-debug_obj): RGBASMFLAGS += -D _SILVER -D _DEBUG

$(BUILD)/%_gold.o: $(BUILD)/%.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_gold.o: %.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_silver.o: $(BUILD)/%.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_silver.o: %.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_gold.d: %.asm | $$(dir $$@) tools/scan_includes
	@tools/scan_includes -b $(BUILD)/ -i $(BUILD)/ -i ./ -o $@ -t $(@:.d=.o) $<

$(BUILD)/%_silver.d: %.asm | $$(dir $$@) tools/scan_includes
	@tools/scan_includes -b $(BUILD)/ -i $(BUILD)/ -i ./ -o $@ -t $(@:.d=.o) $<

$(BUILD)/%_gold_debug.o: $(BUILD)/%.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_gold_debug.o: %.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_silver_debug.o: $(BUILD)/%.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_silver_debug.o: %.asm | $$(dir $$@) rgbdscheck.o
	$(RGBASM) $(RGBASMFLAGS) $(OUTPUT_OPTION) $<

$(BUILD)/%_gold_debug.d: %.asm | $$(dir $$@) tools/scan_includes
	@tools/scan_includes -b $(BUILD)/ -i $(BUILD)/ -i ./ -o $@ -t $(@:.d=.o) $<

$(BUILD)/%_silver_debug.d: %.asm | $$(dir $$@) tools/scan_includes
	@tools/scan_includes -b $(BUILD)/ -i $(BUILD)/ -i ./ -o $@ -t $(@:.d=.o) $<

.PRECIOUS: $(BUILD)/%.pic
$(BUILD)/%.pic: $(BUILD)/%.2bpp tools/pkmncompress | $$(dir $$@)
	tools/pkmncompress $< $@

.PRECIOUS: $(BUILD)/%.2bpp
$(BUILD)/%.2bpp: %.png tools/gfx | $$(dir $$@)
	$(RGBGFX) -c dmg $(RGBGFXFLAGS) $(OUTPUT_OPTION) $<
	tools/gfx $(tools/gfx) $(OUTPUT_OPTION) $@

.PRECIOUS: $(BUILD)/%.1bpp
$(BUILD)/%.1bpp: %.1bpp.png tools/gfx | $$(dir $$@)
	$(RGBGFX) -c dmg $(RGBGFXFLAGS) -d1 $(OUTPUT_OPTION) $<
	tools/gfx $(tools/gfx) -d1 $(OUTPUT_OPTION) $@

.PRECIOUS: $(BUILD)/%.tilemap
$(BUILD)/%.tilemap: %.png | $$(dir $$@)
	$(RGBGFX) -c dmg $(RGBGFXFLAGS) -t $@ $<

.PRECIOUS: $(BUILD)/%.sgb.tilemap
export LC_ALL=C
$(BUILD)/%.sgb.tilemap: %.bin | $$(dir $$@)
	tr < $< -d '\000' > $@

.PRECIOUS: %/
%/:
	mkdir -p $@


### Scan .asm files for INCLUDE dependencies

ifeq (,$(filter clean tools,$(MAKECMDGOALS)))
-include $(patsubst %.o, %.d, $(pokegold-spaceworld_obj) $(pokesilver-spaceworld_obj) $(pokegold-spaceworld-debug_obj) $(pokesilver-spaceworld-debug_obj))
endif
