SECTION "Link Cable Maps", ROMX

INCLUDE "scripts/UnusedGen1TradeCenter.asm"
INCLUDE "data/maps/objects/UnusedGen1TradeCenter.asm"
INCLUDE "scripts/UnusedGen1Colosseum.asm"
INCLUDE "data/maps/objects/UnusedGen1Colosseum.asm"


SECTION "Old City Maps", ROMX

INCLUDE "data/maps/objects/Route2Gate1F.asm"
INCLUDE "scripts/Route2Gate1F.asm"
INCLUDE "data/maps/objects/Route2Gate2F.asm"
INCLUDE "scripts/Route2Gate2F.asm"
INCLUDE "data/maps/objects/Route2House.asm"
INCLUDE "scripts/Route2House.asm"
INCLUDE "data/maps/objects/OldCityMuseum.asm"
INCLUDE "scripts/OldCityMuseum.asm"
INCLUDE "data/maps/objects/OldCityGym.asm"
INCLUDE "scripts/OldCityGym.asm"
INCLUDE "data/maps/objects/OldCityTower1F.asm"
INCLUDE "scripts/OldCityTower1F.asm"
INCLUDE "data/maps/objects/OldCityTower2F.asm"
INCLUDE "scripts/OldCityTower2F.asm"
INCLUDE "data/maps/objects/OldCityTower3F.asm"
INCLUDE "scripts/OldCityTower3F.asm"
INCLUDE "data/maps/objects/OldCityTower4F.asm"
INCLUDE "scripts/OldCityTower4F.asm"
INCLUDE "data/maps/objects/OldCityTower5F.asm"
INCLUDE "scripts/OldCityTower5F.asm"
INCLUDE "data/maps/objects/OldCityBillsHouse.asm"
INCLUDE "scripts/OldCityBillsHouse.asm"
INCLUDE "data/maps/objects/OldCityMart.asm"
INCLUDE "scripts/OldCityMart.asm"
INCLUDE "data/maps/objects/OldCityHouse.asm"
INCLUDE "scripts/OldCityHouse.asm"
INCLUDE "data/maps/objects/OldCityPokecenter1F.asm"
INCLUDE "scripts/OldCityPokecenter1F.asm"
INCLUDE "data/maps/objects/OldCityPokecenter2F.asm"
INCLUDE "scripts/OldCityPokecenter2F.asm"
INCLUDE "data/maps/objects/OldCityPokecenterTrade.asm"
INCLUDE "scripts/OldCityPokecenterTrade.asm"
INCLUDE "data/maps/objects/OldCityPokecenterBattle.asm"
INCLUDE "scripts/OldCityPokecenterBattle.asm"
INCLUDE "data/maps/objects/OldCityPokecenterTimeMachine.asm"
INCLUDE "scripts/OldCityPokecenterTimeMachine.asm"
INCLUDE "data/maps/objects/OldCityKurtsHouse.asm"
INCLUDE "scripts/OldCityKurtsHouse.asm"
INCLUDE "data/maps/objects/OldCitySchool.asm"
INCLUDE "scripts/OldCitySchool.asm"


SECTION "West Maps", ROMX

INCLUDE "data/maps/objects/Route1Gate1F.asm"
INCLUDE "scripts/Route1Gate1F.asm"
INCLUDE "data/maps/objects/Route1Gate2F.asm"
INCLUDE "scripts/Route1Gate2F.asm"
INCLUDE "data/maps/objects/WestMart1F.asm"
INCLUDE "scripts/WestMart1F.asm"
INCLUDE "data/maps/objects/WestMart2F.asm"
INCLUDE "scripts/WestMart2F.asm"
INCLUDE "data/maps/objects/WestMart3F.asm"
INCLUDE "scripts/WestMart3F.asm"
INCLUDE "data/maps/objects/WestMart4F.asm"
INCLUDE "scripts/WestMart4F.asm"
INCLUDE "data/maps/objects/WestMart5F.asm"
INCLUDE "scripts/WestMart5F.asm"
INCLUDE "data/maps/objects/WestMart6F.asm"
INCLUDE "scripts/WestMart6F.asm"
INCLUDE "data/maps/objects/WestMartElevator.asm"
INCLUDE "scripts/WestMartElevator.asm"
INCLUDE "data/maps/objects/WestRadioTower1F.asm"
INCLUDE "scripts/WestRadioTower1F.asm"
INCLUDE "data/maps/objects/WestRadioTower2F.asm"
INCLUDE "scripts/WestRadioTower2F.asm"
INCLUDE "data/maps/objects/WestRadioTower3F.asm"
INCLUDE "scripts/WestRadioTower3F.asm"
INCLUDE "data/maps/objects/WestRadioTower4F.asm"
INCLUDE "scripts/WestRadioTower4F.asm"
INCLUDE "data/maps/objects/WestRadioTower5F.asm"
INCLUDE "scripts/WestRadioTower5F.asm"
INCLUDE "data/maps/objects/WestRocketRaidedHouse.asm"
INCLUDE "scripts/WestRocketRaidedHouse.asm"
INCLUDE "data/maps/objects/WestPokecenter1F.asm"
INCLUDE "scripts/WestPokecenter1F.asm"
INCLUDE "data/maps/objects/WestPokecenter2F.asm"
INCLUDE "scripts/WestPokecenter2F.asm"
INCLUDE "data/maps/objects/WestGym.asm"
INCLUDE "scripts/WestGym.asm"
INCLUDE "data/maps/objects/WestHouse1.asm"
INCLUDE "scripts/WestHouse1.asm"
INCLUDE "data/maps/objects/WestHouse2.asm"
INCLUDE "scripts/WestHouse2.asm"


SECTION "High-Tech Maps", ROMX

INCLUDE "data/maps/objects/HighTechWestRouteGate.asm"
INCLUDE "scripts/HighTechWestRouteGate.asm"
INCLUDE "data/maps/objects/HighTechPokecenter1F.asm"
INCLUDE "scripts/HighTechPokecenter1F.asm"
INCLUDE "data/maps/objects/HighTechPokecenter2F.asm"
INCLUDE "scripts/HighTechPokecenter2F.asm"
INCLUDE "data/maps/objects/HighTechLeague1F.asm"
INCLUDE "scripts/HighTechLeague1F.asm"
INCLUDE "data/maps/objects/HighTechLeague2F.asm"
INCLUDE "scripts/HighTechLeague2F.asm"
INCLUDE "data/maps/objects/HighTechMart.asm"
INCLUDE "scripts/HighTechMart.asm"
INCLUDE "data/maps/objects/HighTechHouse1.asm"
INCLUDE "scripts/HighTechHouse1.asm"
INCLUDE "data/maps/objects/HighTechHouse2.asm"
INCLUDE "scripts/HighTechHouse2.asm"
INCLUDE "data/maps/objects/HighTechImposterOakHouse.asm"
INCLUDE "scripts/HighTechImposterOakHouse.asm"
INCLUDE "data/maps/objects/HighTechAquarium1F.asm"
INCLUDE "scripts/HighTechAquarium1F.asm"
INCLUDE "data/maps/objects/HighTechAquarium2F.asm"
INCLUDE "scripts/HighTechAquarium2F.asm"


SECTION "Font Maps", ROMX

INCLUDE "data/maps/objects/FontRouteGate1.asm"
INCLUDE "scripts/FontRouteGate1.asm"
INCLUDE "data/maps/objects/FontRouteGate2.asm"
INCLUDE "scripts/FontRouteGate2.asm"
INCLUDE "data/maps/objects/FontRouteGate3.asm"
INCLUDE "scripts/FontRouteGate3.asm"
INCLUDE "data/maps/objects/FontRocketHouse.asm"
INCLUDE "scripts/FontRocketHouse.asm"
INCLUDE "data/maps/objects/FontMart.asm"
INCLUDE "scripts/FontMart.asm"
INCLUDE "data/maps/objects/FontHouse.asm"
INCLUDE "scripts/FontHouse.asm"
INCLUDE "data/maps/objects/FontPokecenter1F.asm"
INCLUDE "scripts/FontPokecenter1F.asm"
INCLUDE "data/maps/objects/FontPokecenter2F.asm"
INCLUDE "scripts/FontPokecenter2F.asm"
INCLUDE "data/maps/objects/FontLab.asm"
INCLUDE "scripts/FontLab.asm"


SECTION "Birdon Maps", ROMX

INCLUDE "data/maps/objects/BirdonMart.asm"
INCLUDE "scripts/BirdonMart.asm"
INCLUDE "data/maps/objects/BirdonPokecenter1F.asm"
INCLUDE "scripts/BirdonPokecenter1F.asm"
INCLUDE "data/maps/objects/BirdonPokecenter2F.asm"
INCLUDE "scripts/BirdonPokecenter2F.asm"
INCLUDE "data/maps/objects/BirdonHouse1.asm"
INCLUDE "scripts/BirdonHouse1.asm"
INCLUDE "data/maps/objects/BirdonWallpaperHouse.asm"
INCLUDE "scripts/BirdonWallpaperHouse.asm"
INCLUDE "data/maps/objects/BirdonHouse2.asm"
INCLUDE "scripts/BirdonHouse2.asm"
INCLUDE "data/maps/objects/BirdonLeague1F.asm"
INCLUDE "scripts/BirdonLeague1F.asm"
INCLUDE "data/maps/objects/BirdonLeague2F.asm"
INCLUDE "scripts/BirdonLeague2F.asm"
INCLUDE "data/maps/objects/BirdonRouteGateWest.asm"
INCLUDE "scripts/BirdonRouteGateWest.asm"


SECTION "Newtype Maps", ROMX

INCLUDE "data/maps/objects/BirdonRouteGateNewtype.asm"
INCLUDE "scripts/BirdonRouteGateNewtype.asm"
INCLUDE "data/maps/objects/NewtypePokecenter1F.asm"
INCLUDE "scripts/NewtypePokecenter1F.asm"
INCLUDE "data/maps/objects/NewtypePokecenter2F.asm"
INCLUDE "scripts/NewtypePokecenter2F.asm"
INCLUDE "data/maps/objects/NewtypeLeague1F.asm"
INCLUDE "scripts/NewtypeLeague1F.asm"
INCLUDE "data/maps/objects/NewtypeLeague2F.asm"
INCLUDE "scripts/NewtypeLeague2F.asm"
INCLUDE "data/maps/objects/NewtypeSailorHouse.asm"
INCLUDE "scripts/NewtypeSailorHouse.asm"
INCLUDE "data/maps/objects/NewtypeMart.asm"
INCLUDE "scripts/NewtypeMart.asm"
INCLUDE "data/maps/objects/NewtypeDojo.asm"
INCLUDE "scripts/NewtypeDojo.asm"
INCLUDE "data/maps/objects/NewtypeHouse1.asm"
INCLUDE "scripts/NewtypeHouse1.asm"
INCLUDE "data/maps/objects/NewtypeDiner.asm"
INCLUDE "scripts/NewtypeDiner.asm"
INCLUDE "data/maps/objects/NewtypeHouse2.asm"
INCLUDE "scripts/NewtypeHouse2.asm"
INCLUDE "data/maps/objects/NewtypeHouse3.asm"
INCLUDE "scripts/NewtypeHouse3.asm"
INCLUDE "data/maps/objects/Route15Pokecenter1F.asm"
INCLUDE "scripts/Route15Pokecenter1F.asm"
INCLUDE "data/maps/objects/Route15Pokecenter2F.asm"
INCLUDE "scripts/Route15Pokecenter2F.asm"
INCLUDE "data/maps/objects/NewtypeRouteGate.asm"
INCLUDE "scripts/NewtypeRouteGate.asm"
INCLUDE "data/maps/objects/Route18Pokecenter1F.asm"
INCLUDE "scripts/Route18Pokecenter1F.asm"
INCLUDE "data/maps/objects/Route18Pokecenter2F.asm"
INCLUDE "scripts/Route18Pokecenter2F.asm"


SECTION "Sugar Maps", ROMX

INCLUDE "data/maps/objects/SugarRouteGate.asm"
INCLUDE "scripts/SugarRouteGate.asm"
INCLUDE "data/maps/objects/SugarHouse.asm"
INCLUDE "scripts/SugarHouse.asm"
INCLUDE "data/maps/objects/SugarHouse2.asm"
INCLUDE "scripts/SugarHouse2.asm"
INCLUDE "data/maps/objects/SugarMart.asm"
INCLUDE "scripts/SugarMart.asm"
INCLUDE "data/maps/objects/SugarPokecenter1F.asm"
INCLUDE "scripts/SugarPokecenter1F.asm"
INCLUDE "data/maps/objects/SugarPokecenter2F.asm"
INCLUDE "scripts/SugarPokecenter2F.asm"


SECTION "Blue Forest Maps", ROMX

INCLUDE "data/maps/objects/BlueForestRoute1House.asm"
INCLUDE "scripts/BlueForestRoute1House.asm"
INCLUDE "data/maps/objects/BlueForestRouteGateStand.asm"
INCLUDE "scripts/BlueForestRouteGateStand.asm"
INCLUDE "data/maps/objects/BlueMart.asm"
INCLUDE "scripts/BlueMart.asm"
INCLUDE "data/maps/objects/BlueHouse1.asm"
INCLUDE "scripts/BlueHouse1.asm"
INCLUDE "data/maps/objects/BlueHouse2.asm"
INCLUDE "scripts/BlueHouse2.asm"
INCLUDE "data/maps/objects/BlueHouse3.asm"
INCLUDE "scripts/BlueHouse3.asm"
INCLUDE "data/maps/objects/BluePokecenter1F.asm"
INCLUDE "scripts/BluePokecenter1F.asm"
INCLUDE "data/maps/objects/BluePokecenter2F.asm"
INCLUDE "scripts/BluePokecenter2F.asm"
INCLUDE "data/maps/objects/BlueLeague1F.asm"
INCLUDE "scripts/BlueLeague1F.asm"
INCLUDE "data/maps/objects/BlueLeague2F.asm"
INCLUDE "scripts/BlueLeague2F.asm"
INCLUDE "data/maps/objects/BlueHouse4.asm"
INCLUDE "scripts/BlueHouse4.asm"


SECTION "Stand Maps", ROMX

INCLUDE "data/maps/objects/StandRouteGateKanto.asm"
INCLUDE "scripts/StandRouteGateKanto.asm"
INCLUDE "data/maps/objects/StandLab.asm"
INCLUDE "scripts/StandLab.asm"
INCLUDE "data/maps/objects/StandPokecenter1F.asm"
INCLUDE "scripts/StandPokecenter1F.asm"
INCLUDE "data/maps/objects/StandPokecenter2F.asm"
INCLUDE "scripts/StandPokecenter2F.asm"
INCLUDE "data/maps/objects/StandOffice.asm"
INCLUDE "scripts/StandOffice.asm"
INCLUDE "data/maps/objects/StandMart.asm"
INCLUDE "scripts/StandMart.asm"
INCLUDE "data/maps/objects/StandHouse.asm"
INCLUDE "scripts/StandHouse.asm"
INCLUDE "data/maps/objects/StandRocketHouse1F.asm"
INCLUDE "scripts/StandRocketHouse1F.asm"
INCLUDE "data/maps/objects/StandRocketHouse2F.asm"
INCLUDE "scripts/StandRocketHouse2F.asm"
INCLUDE "data/maps/objects/StandLeague1F.asm"
INCLUDE "scripts/StandLeague1F.asm"
INCLUDE "data/maps/objects/StandLeague2F.asm"
INCLUDE "scripts/StandLeague2F.asm"


SECTION "Kanto Maps", ROMX

INCLUDE "data/maps/objects/KantoCeruleanHouse.asm"
INCLUDE "scripts/KantoCeruleanHouse.asm"
INCLUDE "data/maps/objects/KantoPokecenter1F.asm"
INCLUDE "scripts/KantoPokecenter1F.asm"
INCLUDE "data/maps/objects/KantoPokecenter2F.asm"
INCLUDE "scripts/KantoPokecenter2F.asm"
INCLUDE "data/maps/objects/KantoLeague1F.asm"
INCLUDE "scripts/KantoLeague1F.asm"
INCLUDE "data/maps/objects/KantoLeague2F.asm"
INCLUDE "scripts/KantoLeague2F.asm"
INCLUDE "data/maps/objects/KantoLavenderHouse.asm"
INCLUDE "scripts/KantoLavenderHouse.asm"
INCLUDE "data/maps/objects/KantoCeladonMart1F.asm"
INCLUDE "scripts/KantoCeladonMart1F.asm"
INCLUDE "data/maps/objects/KantoCeladonMart2F.asm"
INCLUDE "scripts/KantoCeladonMart2F.asm"
INCLUDE "data/maps/objects/KantoCeladonMart3F.asm"
INCLUDE "scripts/KantoCeladonMart3F.asm"
INCLUDE "data/maps/objects/KantoCeladonMart4F.asm"
INCLUDE "scripts/KantoCeladonMart4F.asm"
INCLUDE "data/maps/objects/KantoCeladonMart5F.asm"
INCLUDE "scripts/KantoCeladonMart5F.asm"
INCLUDE "data/maps/objects/KantoCeladonElevator.asm"
INCLUDE "scripts/KantoCeladonElevator.asm"
INCLUDE "data/maps/objects/KantoMart.asm"
INCLUDE "scripts/KantoMart.asm"
INCLUDE "data/maps/objects/KantoGamefreakHQ1.asm"
INCLUDE "scripts/KantoGamefreakHQ1.asm"
INCLUDE "data/maps/objects/KantoGamefreakHQ2.asm"
INCLUDE "scripts/KantoGamefreakHQ2.asm"
INCLUDE "data/maps/objects/KantoGamefreakHQ3.asm"
INCLUDE "scripts/KantoGamefreakHQ3.asm"
INCLUDE "data/maps/objects/KantoGamefreakHQ4.asm"
INCLUDE "scripts/KantoGamefreakHQ4.asm"
INCLUDE "data/maps/objects/KantoGamefreakHQ5.asm"
INCLUDE "scripts/KantoGamefreakHQ5.asm"
INCLUDE "data/maps/objects/KantoSilphCo.asm"
INCLUDE "scripts/KantoSilphCo.asm"
INCLUDE "data/maps/objects/KantoViridianHouse.asm"
INCLUDE "scripts/KantoViridianHouse.asm"
INCLUDE "data/maps/objects/KantoGameCorner.asm"
INCLUDE "scripts/KantoGameCorner.asm"
INCLUDE "data/maps/objects/KantoUnusedArea.asm"
INCLUDE "scripts/KantoUnusedArea.asm"
INCLUDE "data/maps/objects/KantoGameCornerPrizes.asm"
INCLUDE "scripts/KantoGameCornerPrizes.asm"
INCLUDE "data/maps/objects/KantoDiner.asm"
INCLUDE "scripts/KantoDiner.asm"
INCLUDE "data/maps/objects/KantoSchool.asm"
INCLUDE "scripts/KantoSchool.asm"
INCLUDE "data/maps/objects/KantoHospital.asm"
INCLUDE "scripts/KantoHospital.asm"
INCLUDE "data/maps/objects/KantoPokecenter21F.asm"
INCLUDE "scripts/KantoPokecenter21F.asm"
INCLUDE "data/maps/objects/KantoPokecenter22F.asm"
INCLUDE "scripts/KantoPokecenter22F.asm"
INCLUDE "data/maps/objects/KantoRedsHouse.asm"
INCLUDE "scripts/KantoRedsHouse.asm"
INCLUDE "data/maps/objects/KantoGreensHouse1F.asm"
INCLUDE "scripts/KantoGreensHouse1F.asm"
INCLUDE "data/maps/objects/KantoGreensHouse2F.asm"
INCLUDE "scripts/KantoGreensHouse2F.asm"
INCLUDE "data/maps/objects/KantoEldersHouse.asm"
INCLUDE "scripts/KantoEldersHouse.asm"
INCLUDE "data/maps/objects/KantoOaksLab.asm"
INCLUDE "scripts/KantoOaksLab.asm"
INCLUDE "data/maps/objects/KantoLeague21F.asm"
INCLUDE "scripts/KantoLeague21F.asm"
INCLUDE "data/maps/objects/KantoLeague22F.asm"
INCLUDE "scripts/KantoLeague22F.asm"
INCLUDE "data/maps/objects/KantoFishingGuru.asm"
INCLUDE "scripts/KantoFishingGuru.asm"


SECTION "South Maps", ROMX

INCLUDE "data/maps/objects/SouthHouse1.asm"
INCLUDE "scripts/SouthHouse1.asm"
INCLUDE "data/maps/objects/SouthPokecenter1F.asm"
INCLUDE "scripts/SouthPokecenter1F.asm"
INCLUDE "data/maps/objects/SouthPokecenter2F.asm"
INCLUDE "scripts/SouthPokecenter2F.asm"
INCLUDE "data/maps/objects/SouthMart.asm"
INCLUDE "scripts/SouthMart.asm"
INCLUDE "data/maps/objects/SouthHouse2.asm"
INCLUDE "scripts/SouthHouse2.asm"


SECTION "North Maps", ROMX

INCLUDE "data/maps/objects/NorthHouse1.asm"
INCLUDE "scripts/NorthHouse1.asm"
INCLUDE "data/maps/objects/NorthMart.asm"
INCLUDE "scripts/NorthMart.asm"
INCLUDE "data/maps/objects/NorthHouse2.asm"
INCLUDE "scripts/NorthHouse2.asm"
INCLUDE "data/maps/objects/NorthPokecenter1F.asm"
INCLUDE "scripts/NorthPokecenter1F.asm"
INCLUDE "data/maps/objects/NorthPokecenter2F.asm"
INCLUDE "scripts/NorthPokecenter2F.asm"


SECTION "Misc Maps", ROMX

INCLUDE "data/maps/objects/PowerPlant1.asm"
INCLUDE "scripts/PowerPlant1.asm"
INCLUDE "data/maps/objects/PowerPlant2.asm"
INCLUDE "scripts/PowerPlant2.asm"
INCLUDE "data/maps/objects/PowerPlant3.asm"
INCLUDE "scripts/PowerPlant3.asm"
INCLUDE "data/maps/objects/PowerPlant4.asm"
INCLUDE "scripts/PowerPlant4.asm"
INCLUDE "data/maps/objects/RuinsOfAlphEntrance.asm"
INCLUDE "scripts/RuinsOfAlphEntrance.asm"
INCLUDE "data/maps/objects/RuinsOfAlphMain.asm"
INCLUDE "scripts/RuinsOfAlphMain.asm"
INCLUDE "data/maps/objects/CaveMinecarts1.asm"
INCLUDE "scripts/CaveMinecarts1.asm"
INCLUDE "data/maps/objects/CaveMinecarts2.asm"
INCLUDE "scripts/CaveMinecarts2.asm"
INCLUDE "data/maps/objects/CaveMinecarts3.asm"
INCLUDE "scripts/CaveMinecarts3.asm"
INCLUDE "data/maps/objects/CaveMinecarts4.asm"
INCLUDE "scripts/CaveMinecarts4.asm"
INCLUDE "data/maps/objects/CaveMinecarts5.asm"
INCLUDE "scripts/CaveMinecarts5.asm"
INCLUDE "data/maps/objects/CaveMinecarts6.asm"
INCLUDE "scripts/CaveMinecarts6.asm"
INCLUDE "data/maps/objects/CaveMinecarts7.asm"
INCLUDE "scripts/CaveMinecarts7.asm"
INCLUDE "data/maps/objects/Office1.asm"
INCLUDE "scripts/Office1.asm"
INCLUDE "data/maps/objects/Office2.asm"
INCLUDE "scripts/Office2.asm"
INCLUDE "data/maps/objects/Office3.asm"
INCLUDE "scripts/Office3.asm"
INCLUDE "data/maps/objects/SlowpokeWellEntrance.asm"
INCLUDE "scripts/SlowpokeWellEntrance.asm"
INCLUDE "data/maps/objects/SlowpokeWellMain.asm"
INCLUDE "scripts/SlowpokeWellMain.asm"
INCLUDE "data/maps/objects/SilentHills.asm"
INCLUDE "scripts/SilentHills.asm"


SECTION "Silent Hill Maps", ROMX

INCLUDE "data/maps/objects/RouteSilentEastGate.asm"
INCLUDE "scripts/RouteSilentEastGate.asm"
INCLUDE "data/maps/objects/PlayerHouse1F.asm"
INCLUDE "scripts/PlayerHouse1F.asm"
INCLUDE "data/maps/objects/PlayerHouse2F.asm"
INCLUDE "scripts/PlayerHouse2F.asm"
INCLUDE "data/maps/objects/SilentHillPokecenter.asm"
INCLUDE "scripts/SilentHillPokecenter.asm"
INCLUDE "data/maps/objects/SilentHillHouse.asm"
INCLUDE "scripts/SilentHillHouse.asm"
INCLUDE "data/maps/objects/SilentHillLabFront.asm"
INCLUDE "scripts/SilentHillLabFront.asm"
INCLUDE "data/maps/objects/SilentHillLabBack.asm"
INCLUDE "scripts/SilentHillLabBack.asm"
INCLUDE "data/maps/objects/UnusedMap13.asm"
INCLUDE "scripts/UnusedMap13.asm"


SECTION "Town Maps", ROMX

INCLUDE "scripts/dummy_text_pointers.asm"
INCLUDE "data/maps/objects/SilentHill.asm"
INCLUDE "data/maps/objects/OldCity.asm"
INCLUDE "scripts/OldCity.asm"
INCLUDE "data/maps/objects/West.asm"
INCLUDE "scripts/West.asm"
INCLUDE "data/maps/objects/HighTech.asm"
INCLUDE "scripts/HighTech.asm"
INCLUDE "data/maps/objects/Font.asm"
INCLUDE "scripts/Font.asm"
INCLUDE "data/maps/objects/Birdon.asm"
INCLUDE "scripts/Birdon.asm"
INCLUDE "data/maps/objects/Newtype.asm"
INCLUDE "scripts/Newtype.asm"
INCLUDE "data/maps/objects/Sugar.asm"
INCLUDE "scripts/Sugar.asm"
INCLUDE "data/maps/objects/BlueForest.asm"
INCLUDE "scripts/BlueForest.asm"
INCLUDE "data/maps/objects/Stand.asm"
INCLUDE "scripts/Stand.asm"
INCLUDE "data/maps/objects/Kanto.asm"
INCLUDE "scripts/Kanto.asm"
INCLUDE "data/maps/objects/Prince.asm"
INCLUDE "scripts/Prince.asm"
INCLUDE "data/maps/objects/MtFuji.asm"
INCLUDE "scripts/MtFuji.asm"
INCLUDE "data/maps/objects/South.asm"
INCLUDE "scripts/South.asm"
INCLUDE "data/maps/objects/North.asm"
INCLUDE "scripts/North.asm"


SECTION "Route Maps", ROMX

INCLUDE "data/maps/objects/Route1P1.asm"
INCLUDE "data/maps/objects/Route1P2.asm"
INCLUDE "data/maps/objects/Route2.asm"
INCLUDE "scripts/Route2.asm"
INCLUDE "data/maps/objects/HighTechWestRoute.asm"
INCLUDE "scripts/HighTechWestRoute.asm"
INCLUDE "data/maps/objects/HighTechWestRouteOcean.asm"
INCLUDE "scripts/HighTechWestRouteOcean.asm"
INCLUDE "data/maps/objects/FontRoute1.asm"
INCLUDE "scripts/FontRoute1.asm"
INCLUDE "data/maps/objects/FontRoute6.asm"
INCLUDE "scripts/FontRoute6.asm"
INCLUDE "data/maps/objects/FontRoute2.asm"
INCLUDE "scripts/FontRoute2.asm"
INCLUDE "data/maps/objects/FontRoute4.asm"
INCLUDE "scripts/FontRoute4.asm"
INCLUDE "data/maps/objects/FontRoute3.asm"
INCLUDE "scripts/FontRoute3.asm"
INCLUDE "data/maps/objects/BirdonRoute1.asm"
INCLUDE "scripts/BirdonRoute1.asm"
INCLUDE "data/maps/objects/BirdonRoute2.asm"
INCLUDE "scripts/BirdonRoute2.asm"
INCLUDE "data/maps/objects/BirdonRoute3.asm"
INCLUDE "scripts/BirdonRoute3.asm"
INCLUDE "data/maps/objects/Route15.asm"
INCLUDE "scripts/Route15.asm"
INCLUDE "data/maps/objects/NewtypeRoute.asm"
INCLUDE "scripts/NewtypeRoute.asm"
INCLUDE "data/maps/objects/Route18.asm"
INCLUDE "scripts/Route18.asm"
INCLUDE "data/maps/objects/BlueForestRoute1.asm"
INCLUDE "scripts/BlueForestRoute1.asm"
INCLUDE "data/maps/objects/SugarRoute.asm"
INCLUDE "scripts/SugarRoute.asm"
INCLUDE "data/maps/objects/BlueForestRoute2.asm"
INCLUDE "scripts/BlueForestRoute2.asm"
INCLUDE "data/maps/objects/StandRoute.asm"
INCLUDE "scripts/StandRoute.asm"
INCLUDE "data/maps/objects/KantoEastRoute.asm"
INCLUDE "scripts/KantoEastRoute.asm"
INCLUDE "data/maps/objects/RouteSilentEast.asm"
INCLUDE "scripts/RouteSilentEast.asm"
INCLUDE "data/maps/objects/PrinceRoute.asm"
INCLUDE "scripts/PrinceRoute.asm"
INCLUDE "data/maps/objects/MtFujiRoute.asm"
INCLUDE "scripts/MtFujiRoute.asm"
INCLUDE "data/maps/objects/FontRoute5.asm"
INCLUDE "scripts/FontRoute5.asm"
INCLUDE "data/maps/objects/BlueForestRoute3.asm"
INCLUDE "scripts/BlueForestRoute3.asm"


SECTION "Silent Hill Scripts", ROMX

INCLUDE "scripts/SilentHill.asm"


SECTION "Route Scripts", ROMX

INCLUDE "scripts/DeletedMap.asm"
INCLUDE "scripts/Route1P1.asm"
INCLUDE "scripts/Route1P2.asm"
