INCLUDE "constants.asm"

SECTION "audio/sfx_pointers.asm", ROMX

SFX::
; entries correspond to SFX_* constants
	dba Sfx_BallWobble
	dba Sfx_Potion
	dba Sfx_FullHeal
	dba Sfx_Menu
	dba Sfx_ReadText
	dba Sfx_ReadText
	dba Sfx_Poison
	dba Sfx_TradeMachine
	dba Sfx_BootPC
	dba Sfx_ShutDownPC
	dba Sfx_ChoosePCOption
	dba Sfx_EscapeRope
	dba Sfx_PressSwitch
	dba Sfx_HealingMachine
	dba Sfx_WarpTo
	dba Sfx_TeleportEnter1
	dba Sfx_TeleportExit2
	dba Sfx_JumpOverLedge
	dba Sfx_TeleportEnter2
	dba Sfx_Fly
	dba Sfx_Wrong
	dba Sfx_ArrowTiles
	dba Sfx_Strength
	dba Sfx_Megaphone
	dba Sfx_WithdrawDeposit
	dba Sfx_CutRG
	dba Sfx_GoInside
	dba Sfx_SwitchPokemon
	dba Sfx_BellyDrum
	dba Sfx_Purchase
	dba Sfx_Collision
	dba Sfx_GoOutside
	dba Sfx_Save
	dba Sfx_Pokeflute
	dba Sfx_SafariZonePA
	dba Sfx_ThrowBall
	dba Sfx_BallPoof
	dba Sfx_Faint
	dba Sfx_Run
	dba Sfx_PokedexRegistration
	dba Sfx_IntroLungeRG
	dba Sfx_Unknown29
	dba Sfx_Unknown2a
	dba Sfx_IntroRaiseRG
	dba Sfx_IntroCrashRG
	dba Sfx_TitleEntrance
	dba Sfx_SlotsStopWheel
	dba Sfx_SlotsReward
	dba Sfx_PayDay
	dba Sfx_GameFreakLogoRG
	dba Sfx_Peck
	dba Sfx_Kinesis
	dba Sfx_Lick
	dba Sfx_Pound
	dba Sfx_Thrash
	dba Sfx_CometPunch
	dba Sfx_MegaPunch
	dba Sfx_Scratch
	dba Sfx_ViceGrip
	dba Sfx_RazorWind
	dba Sfx_Cut
	dba Sfx_WingAttack
	dba Sfx_Whirlwind
	dba Sfx_Bind
	dba Sfx_VineWhip
	dba Sfx_DoubleKick
	dba Sfx_MegaKick
	dba Sfx_Headbutt
	dba Sfx_HornAttack
	dba Sfx_Tackle
	dba Sfx_PoisonSting
	dba Sfx_Powder
	dba Sfx_Doubleslap
	dba Sfx_Bite
	dba Sfx_JumpKick
	dba Sfx_Stomp
	dba Sfx_TailWhip
	dba Sfx_KarateChop
	dba Sfx_Submission
	dba Sfx_WaterGun
	dba Sfx_SwordsDance
	dba Sfx_Thunder
	dba Sfx_Supersonic
	dba Sfx_Leer
	dba Sfx_Ember
	dba Sfx_Bubblebeam
	dba Sfx_HydroPump
	dba Sfx_Surf
	dba Sfx_Psybeam
	dba Sfx_Charge
	dba Sfx_Thundershock
	dba Sfx_Psychic
	dba Sfx_Screech
	dba Sfx_BoneClub
	dba Sfx_Sharpen
	dba Sfx_EggBomb
	dba Sfx_Sing
	dba Sfx_HyperBeam
	dba Sfx_Shine
	dba Sfx_GetItemRG
	dba Sfx_UnusedFanfare1
	dba Sfx_PokedexEvaluationRG
	dba Sfx_LevelUpRG
	dba Sfx_EvolutionCompleteRG
	dba Sfx_GetKeyItemRG
	dba Sfx_UnusedFanfare2
	dba Sfx_CaughtPokemonRG
	dba Sfx_UnusedFanfare3
