INCLUDE "constants.asm"

SECTION "audio/sfx_pointers.asm", ROMX

SFX::
; entries correspond to SFX_* constants
	dba Sfx_00
	dba Sfx_Potion
	dba Sfx_FullHeal
	dba Sfx_Menu
	dba Sfx_ReadText
	dba Sfx_ReadText
	dba Sfx_06
	dba Sfx_07
	dba Sfx_08
	dba Sfx_09
	dba Sfx_BootPC
	dba Sfx_EscapeRope
	dba Sfx_0c
	dba Sfx_0d
	dba Sfx_0e
	dba Sfx_0f
	dba Sfx_10
	dba Sfx_11
	dba Sfx_12
	dba Sfx_13
	dba Sfx_Wrong
	dba Sfx_15
	dba Sfx_16
	dba Sfx_17
	dba Sfx_18
	dba Sfx_19
	dba Sfx_1a
	dba Sfx_SwitchPokemon
	dba Sfx_1c
	dba Sfx_1d
	dba Sfx_1e
	dba Sfx_1f
	dba Sfx_20
	dba Sfx_Pokeflute
	dba Sfx_22
	dba Sfx_23
	dba Sfx_24
	dba Sfx_25
	dba Sfx_26
	dba Sfx_PokedexRegistration
	dba Sfx_28
	dba Sfx_29
	dba Sfx_2a
	dba Sfx_2b
	dba Sfx_2c
	dba Sfx_TitleEntrance
	dba Sfx_2e
	dba Sfx_2f
	dba Sfx_PayDay
	dba Sfx_GameFreakLogoRG
	dba Sfx_32
	dba Sfx_33
	dba Sfx_34
	dba Sfx_35
	dba Sfx_36
	dba Sfx_37
	dba Sfx_38
	dba Sfx_39
	dba Sfx_3a
	dba Sfx_3b
	dba Sfx_3c
	dba Sfx_3d
	dba Sfx_3e
	dba Sfx_3f
	dba Sfx_40
	dba Sfx_41
	dba Sfx_42
	dba Sfx_43
	dba Sfx_44
	dba Sfx_45
	dba Sfx_46
	dba Sfx_47
	dba Sfx_48
	dba Sfx_49
	dba Sfx_4a
	dba Sfx_4b
	dba Sfx_4c
	dba Sfx_4d
	dba Sfx_4e
	dba Sfx_4f
	dba Sfx_50
	dba Sfx_51
	dba Sfx_52
	dba Sfx_53
	dba Sfx_54
	dba Sfx_55
	dba Sfx_56
	dba Sfx_57
	dba Sfx_58
	dba Sfx_59
	dba Sfx_5a
	dba Sfx_5b
	dba Sfx_5c
	dba Sfx_5d
	dba Sfx_5e
	dba Sfx_5f
	dba Sfx_60
	dba Sfx_61
	dba Sfx_62
	dba Sfx_GetItemRG
	dba Sfx_UnusedFanfare1
	dba Sfx_PokedexEvaluationRG
	dba Sfx_LevelUpRG
	dba Sfx_EvolutionCompleteRG
	dba Sfx_GetKeyItemRG
	dba Sfx_UnusedFanfare2
	dba Sfx_CaughtPokemonRG
	dba Sfx_UnusedFanfare3
