SongHeaderPointers:
	dbw Bank(Song_None), Song_None
	dbw Bank(Song_Title), Song_Title
	dbw Bank(Song_Route1), Song_Route1
	dbw Bank(Song_OakIntro), Song_OakIntro
	dbw Bank(Song_LeaderBattle), Song_LeaderBattle
	dbw Bank(Song_TrainerBattle), Song_TrainerBattle
	dbw Bank(Song_NidorinoIntro), Song_NidorinoIntro
	dbw Bank(Song_ViridianCity), Song_ViridianCity
	dbw Bank(Song_Heal), Song_Heal
	dbw Bank(Song_Bicycle), Song_Bicycle
	dbw Bank(Song_SpottedRocket), Song_SpottedRocket
	dbw Bank(Song_VictoryTrainer), Song_VictoryTrainer
	dbw Bank(Song_Evolution), Song_Evolution
