AnnonPicPtrs::
AnnonPicPtrsFront::
	dw AnnonAPicFront
AnnonPicPtrsBack::
	dw AnnonAPicBack
	dw AnnonBPicFront
	dw AnnonBPicBack
	dw AnnonCPicFront
	dw AnnonCPicBack
	dw AnnonDPicFront
	dw AnnonDPicBack
	dw AnnonEPicFront
	dw AnnonEPicBack
	dw AnnonFPicFront
	dw AnnonFPicBack
	dw AnnonGPicFront
	dw AnnonGPicBack
	dw AnnonHPicFront
	dw AnnonHPicBack
	dw AnnonIPicFront
	dw AnnonIPicBack
	dw AnnonJPicFront
	dw AnnonJPicBack
	dw AnnonKPicFront
	dw AnnonKPicBack
	dw AnnonLPicFront
	dw AnnonLPicBack
	dw AnnonMPicFront
	dw AnnonMPicBack
	dw AnnonNPicFront
	dw AnnonNPicBack
	dw AnnonOPicFront
	dw AnnonOPicBack
	dw AnnonPPicFront
	dw AnnonPPicBack
	dw AnnonQPicFront
	dw AnnonQPicBack
	dw AnnonRPicFront
	dw AnnonRPicBack
	dw AnnonSPicFront
	dw AnnonSPicBack
	dw AnnonTPicFront
	dw AnnonTPicBack
	dw AnnonUPicFront
	dw AnnonUPicBack
	dw AnnonVPicFront
	dw AnnonVPicBack
	dw AnnonWPicFront
	dw AnnonWPicBack
	dw AnnonXPicFront
	dw AnnonXPicBack
	dw AnnonYPicFront
	dw AnnonYPicBack
	dw AnnonZPicFront
	dw AnnonYPicBack  ; typo in original list
