name: CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  rgbds_version: v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout rgbds
        uses: actions/checkout@v6
        with:
          path: rgbds
          ref: ${{ env.rgbds_version }}
          repository: gbdev/rgbds

      - name: Install rgbds
        working-directory: rgbds
        run: |
          sudo apt-get update
          sudo apt-get install -yq bison libpng-dev pkg-config
          sudo make -j$(nproc) install

      - name: Remove rgbds
        run: |
          rm -rf rgbds

      - name: Cache baseroms
        id: cache-baseroms
        uses: actions/cache@v5
        with:
          path: baserom-gold.gb baserom-silver.gb
          key: ${{ runner.os }}-baseroms

      - name: Download baseroms
        if: steps.cache-baseroms.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install wget p7zip-full
          wget -O gold-debug.7z 'https://tcrf.net/images/3/33/Pok%C3%A9mon_Gold_-_Spaceworld_1997_Demo_%28Debug%29.7z'
          wget -O silver-debug.7z 'https://tcrf.net/images/b/b2/Pok%C3%A9mon_Silver_-_Spaceworld_1997_Demo_%28Debug%29.7z'
          7z e gold-debug.7z
          mv P*\(Debug\).sgb baserom-gold.gb
          7z e gold-debug.7z
          mv P*\(Debug\).sgb baserom-silver.gb
          rm -f *.7z P*\(Header\ Fixed\).sgb

      - name: Compare
        run: |
          make -j$(nproc) compare
          if ! git diff-index --quiet HEAD --; then
            echo 'Uncommitted changes detected:'
            git diff-index HEAD --
            return 1
          fi
